<div class="congratulation_container">
<!--	<div class="lh30">&nbsp;</div>-->
	<div class="floatLeft">
		<div class="congratulation_text">Congratulations!!</div>
		<div class="congratulation_desc">Your demo Goo2o store has been created.</div>
	</div>
	<div class="lh60">&nbsp;</div>
	<div class="congratulation_innercontainer">
		<div align="center"><a href=" <?php echo HTTP_SERVER ;?>/admin/overview/#page" alt="MANAGE YOUR STORE" title="MANAGE YOUR STORE" class="manageyourstore"></a></div>
		<div class="congratulation_innercontent">Start designing and adding products</div>
		<div class="lh30">&nbsp;</div>
		<div class="borderbottom"></div>
	</div>
	<div class="lh35">&nbsp;</div>
	<div class="congratulation_innercontainer">
		<div align="center"><a href=" <?php echo $this->mallurl; ?>" title="VIEW YOUR STORE" alt="VIEW YOUR STORE" target="_blank" class="viewyourstore"></a></div>
		<div class="congratulation_innercontent">This is what your customers will see</div>
		<div class="lh30">&nbsp;</div>
		<div class="borderbottom"></div>
	</div>
	<div class="lh55">&nbsp;</div>
	<div class="congratulation_content">You have 15 days left in your trial. You can upgrade to a paid plan at any time without loosing your data.</div>
	<div class="lh30">&nbsp;</div>
	<div class="congratulation_desc" align="center">You can always call us for support at  <span class="phoneno">+91.124.398.3111</span></div>
	<div align="center" class="congratulation_desc">Or mail us at <a href="mailto:support@goo2o.com" class="support_link" title="support@goo2o.com">support@goo2o.com</a></div>
</div>