<div style="color:#0083CB;font-size:22px; margin-top:50px; text-align:center;">Your Store is Being Created, Please Wait...</div>
<div style="color:#0083CB;font-size:14px;margin-top:10px; text-align:center;">Thanks for choosing goo2o. We're creating your store now.</div>
<div style="color:#0083CB;font-size:14px; margin-top:10px; text-align:center;">Please don't refresh this page.</div>
<div style="margin-top:70px;text-align:center;" align="center"><img src="http://goo2ostore.com/bar/images/goo2oloading.gif"></div>