<!--<div class="congratulation_container">
	<div class="floatLeft">
		<div class="congratulation_text">Congratulations!!</div>
		<div class="congratulation_desc">You have successfully created your online demo store. </div>
	</div>
	<div class="lh30">&nbsp;</div>
	<div class="clearBoth contentText14">
		<div class="wid142">Store Name</div>
		<div class="wid24">:</div>
		<div class="wid300"> <b><?php //echo $this->storesname; ?></b></div>
	</div>
	<div class="lh7">&nbsp;</div>
	<div class="clearBoth contentText14">
		<div class="wid142">Store URL</div>
		<div class="wid24">:</div>
		<div class="wid300"><a href="<?php //echo $this->mallurl; ?>" title="<?php //echo $this->mallurl; ?>" class="hyperLinkB14" target="_blank"><?php //echo $this->mallurl; ?></a></div>
	</div>
	
	<div class="lh60">&nbsp;</div>
	<div class="congratulation_innercontainer">
		<div align="center"><a href="<?php //echo HTTP_SERVER ;?>/admin/overview/#page"><img src="/images/secure/demo/manage_yourstore_btn.png" alt="MANAGE YOUR STORE" title="MANAGE YOUR STORE" /></a></div>
		<div class="congratulation_innercontent">Start designing and adding products</div>
		<div class="lh30">&nbsp;</div>
		<div class="borderbottom"></div>
	</div>
	<div class="lh35">&nbsp;</div>
	<div class="congratulation_innercontainer">
		<div align="center"><a href="<?php //echo $this->mallurl; ?>" target="_blank"><img src="/images/secure/demo/view_yourstore_btn.png" alt="VIEW YOUR STORE" title="VIEW YOUR STORE" /></a></div>
		<div class="congratulation_innercontent">This is what your customers will see</div>
		<div class="lh30">&nbsp;</div>
		<div class="borderbottom"></div>
	</div>
	<div class="lh55">&nbsp;</div>
	<div class="congratulation_content">You have <?php //echo $this->days ;?> days left in your trial. You can upgrade to a paid plan at any time without loosing your data.</div>
	<div class="lh30">&nbsp;</div>
	<div class="congratulation_desc" align="center">You can always call us for support at  <span class="phoneno">+91.124.398.3111</span></div>
	<div align="center" class="congratulation_desc">Or mail us at <a href="mailto:support@goo2o.com" class="support_link" title="support@goo2o.com">support@goo2o.com</a></div>
</div>-->
<div class="congratulation_container">
	
	<div class="floatLeft">
		<div class="congratulation_text">Congratulations!!</div>
		<div class="congratulation_desc">You have successfully created your online store. </div>
	</div>
	<div class="lh30">&nbsp;</div>
	<div class="clearBoth contentText14">
		<div class="wid142">Store Name</div>
		<div class="wid24">:</div>
		<div class="wid300"> <b><?php echo $this->storesname; ?></b></div>
	</div>
	<div class="lh7">&nbsp;</div>
	<div class="clearBoth contentText14">
		<div class="wid142">Store Domain</div>
		<div class="wid24">:</div>
		<div class="wid300"><a href="<?php echo $this->mallurl; ?>" title="<?php echo $this->mallurl; ?>" class="hyperLinkB14" target="_blank"><?php echo $this->mallurl; ?></a></div>
	</div>
	
	<div class="lh110">&nbsp;</div>
	<div class="btnsCont">
		<div align="center"><a href="<?php echo HTTP_SERVER ;?>/admin/overview/#page"><img src="/images/secure/demo/manage_yourstore_btn.png" alt="MANAGE YOUR STORE" title="MANAGE YOUR STORE" /></a></div>
		<div class="congratulation_innercontent">Start designing and adding products</div>
		<div class="lh30">&nbsp;</div>
		
	</div>

	<div class="floatLeft">
		<div class="wid235">
			<div align="center"><a href="<?php echo $this->mallurl; ?>" target="_blank"><img src="/images/secure/demo/view_yourstore_btn.png" alt="VIEW YOUR STORE" title="VIEW YOUR STORE" /></a></div>
			<div class="congratulation_innercontent">This is what your customers will see</div>
			<div class="lh30">&nbsp;</div>
		</div>
	
		
	</div>
	<div class="lh160">&nbsp;</div>
	<div class="botFooterLine">You have <?php echo $this->days ;?> days left in your trial. You can upgrade to a paid plan at any time without loosing your data.
Need help? visit our <a href="http://support.goingo2o.com/" title="support center" class="hyper_link14" target="_blank">support center</a></div>
</div>