<div id="wid1000Auto">
	<!--<div id="header-wrapper">
		<div id="logo"><a href="#" title="Goo2o"><img src="/images/secure/registration/logo_blue.gif" alt="logo" /></a></div>
        <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>
        </div>-->
    <div class="clearBoth">
    	<div class="blueMainHeadingContainer">
    		<div class="blueMainHeading">E-mail Address/User Name Already in Use</div>
        </div>
        <div class="lh40">&nbsp;</div>
        <div class="email_error_msgBox">
        	<div class="floatLeft"><img src="/images/secure/registration/email_error_msg_img.gif" alt="" /></div>
            <div class="floatLeft">
            	<div class="clearBoth content-text14"><b>There was a problem with your request</b></div>
                <div class="lh7">&nbsp;</div>
                <div class="content-text12">You indicated you don't have a Goo2o ID, but an account with <b><?php echo $_REQUEST['username']."". $_REQUEST['user_email_address'];?></b> already exists.</div>
            </div>
       	</div>
        <div class="lh32">&nbsp;</div>
        <div class="clearBoth content-text12"><b>Already own a Goo2o ID?</b></div>
        <div class="lh5">&nbsp;</div>
        <div class="clearBoth"><a href="<?php echo HTTP_SECURE;?>/login" class="hyperLinkBlue12" title="Sign in">Sign in</a></div>
        <div class="lh5">&nbsp;</div>
        <div class="clearBoth"><a href="<?php echo HTTP_SECURE;?>/login/forgetpassword" class="hyperLinkBlue12" title="Forgot your password?">Forgot your password?</a></div>
        <div class="lh25">&nbsp;</div>

        <div class="clearBoth content-text12"><b>New to Goo2o.com?</b></div>
        <div class="lh5">&nbsp;</div>
        <div class="content-text12">Create a new Goo2o ID with a <a href="<?php echo HTTP_SECURE;?>/registration" class="hyperLinkBlue12" title="different email address">different email address</a></div>
 	</div>
</div>
