<div id="wid1000Auto">
	<!--<div id="header-wrapper">
		<div id="logo"><a href="#" title="Goo2o"><img src="/images/secure/registration/logo_blue.gif" alt="logo" /></a></div>
        <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>
    </div>-->
    <div class="blueMainHeadingContainer">
    	<div class="blueMainHeading floatLeft">Your email address has been Confirmed!</div>
   	</div>

    <div class="clearBoth">
    	<div class="lh40">&nbsp;</div>
        <div class="clearBoth content-text14">Thanks for joining Goo2o. We hope you’re going to love it, just like all the other members do <b>:)</b></div>
        <div class="lh10">&nbsp;</div>
    	<div class="clearBoth content-text14">Your email <span class="content-textGreen18"><?php echo $this->username; ?></span> has now been verified.</div>


        <div class="lh75">&nbsp;</div>
        <div class="floatLeft">
         <form action="" method="post" name="proceedform" id="proceedform">
          <input type="hidden"  id="useremail" name="useremail" value="<?php echo $this->username; ?>"/>
          <a href="<?php echo HTTP_SERVER.'/myaccount'; ?>"><img src="/images/secure/registration/proceed_to_your_account_btn.gif" class="cursor" title="Proceed to your account"></a>
         </form>
        </div>

    </div>
</div>
