<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>
<script>
	jQuery(document).ready(function(){
		jQuery('.checkboxclass').click(function(){
			jQuery(this).removeClass('checkbox_off') .addClass('checkbox_on');
		});
	});
</script>

<div id="wid1000Auto">
	<!--<div id="header-wrapper">
		<div id="logo"><a href="#" title="Goo2o"><img src="/images/secure/registration/logo_blue.gif" alt="logo" /></a></div>
        <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>
    </div>-->
    <div class="clearBoth">
    	<div class="blueMainHeadingContainer">
    		<div class="blueMainHeading">Sign in</div>
        </div>
        <div class="lh50">&nbsp;</div>
        <div class="clearBoth">
        	<div class="wid263AlignR content-text12Lh20">Enter your email address/username</div>
            <div class="wid23AlignC content-text12Lh20">:</div>
            <div class="wid415">
            	<div class="clearBoth"><input type="text" class="input-textField230" id="txtname"/></div>
                <div class="lh32">&nbsp;</div>
                <div class="clearBoth">
                	<div class="clearBoth">
                        <div class="wid25"><input type="radio" name="customer" /></div>
                        <div class="floatLeft">
                            <div class="clearBoth content-text12"><b>I am a new customer</b></div>
                            <div class="lh5">&nbsp;</div>
                            <div class="floatLeft content-text11">(You’ll create a password later)</div>
                        </div>
                	</div>
                    <div class="lh20">&nbsp;</div>
                    <div class="clearBoth">
                        <div class="wid25"><input type="radio" name="customer" /></div>
                        <div class="floatLeft">
                            <div class="clearBoth content-text12 wid160"><b>I am a returning customer, and my password is:</b></div>
                            <div class="lh5">&nbsp;</div>
                            <div class="floatLeft"><input type="text" class="input-textField158" onfocus="document.getElementById('show_hide').style.display='block'" onblur="document.getElementById('show_hide').style.display='none';" /></div>
                            <div class="suggestive-container" id="show_hide">
                            	<div class="floatLeft"><img src="/images/secure/registration/suggestive-left-arrow.gif" height="22" alt="Left arrow" /></div>
                                <div class="suggestive-textContainer">It can’t be blank</div>
                                <div class="floatLeft"><img src="/images/secure/registration/suggestive-right-curve.gif" height="22px" alt="Right curve" /></div>
                            
                            </div>
                            <div class="lh15">&nbsp;</div>
		                    <div class="clearBoth"><a href="forgot_your_password.php" title="Forgot your password?" class="hyperLinkBlue11">Forgot your password?</a></div>
                        </div>
                	</div>
                </div>
            </div>
        	<div class="sign_in_errorMsgBox floatLeft">Wrong username/email and password combination!</div>
        </div>
        <div class="lh35">&nbsp;</div>
        <div class="clearBoth">
        	<div class="wid263AlignR content-text12Lh20">Are you human?</div>
            <div class="wid23AlignC content-text12Lh20">:</div>
            <div class="floatLeft">
            	<div class="clearBoth content-text12Lh20">Type the characters you see in the picture below.</div>
                <div class="lh5">&nbsp;</div>
                <div class="clearBoth"><div class="floatLeft jCaptcha"><?php  echo recaptcha_get_html($this->publickey, $errorRecaptcha); ?></div>
                <div class="lh40">&nbsp;</div>
        		<div class="clearBoth">
        			<div class="checkBox"><label class="checkbox_off checkboxclass"><input type="checkbox" class="input_checkbox" /></label></div>
            		<div class="floatLeft content-text12">Keep me logged in</div>
        		</div>
        		<div class="lh15">&nbsp;</div>
                <div class="clearBoth">
                <input type="submit" class="loginupbtn" title="Sign in using our secure server"  id="submit"  value="" name="signin" />
                </div>
            </div>
        </div>
        <div class="lh35">&nbsp;</div>
    </div>

</div>
</div>
