rerwrrwerwerwerewr
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>People</title>
<?php echo $this->cssHelper();  ?>
<?php echo $this->headLink()->appendStylesheet('/css/default/people.css');?>
<?php echo $this->javascriptHelper();  ?></head>
<body>
<div class="wid100per" style="position:fixed; z-index:9998;">
	<div class="header_bg">
		<div class="wid1000">
			<div class="logo_o2obg"><a href="#"><img src="/images/logo_o2o.gif" alt="goo20" title="goo2o" /></a></div>
			<div class="header_menu">
				<ul>
					<li>
						<a href="#" title="Home">
						<div class="wid31">
							<div class="home_icon"></div>
							<div class="paddtop7">Home</div>
						</div>
						</a>
					</li>
					<li>
						<a href="#" title="Profile">
						<div class="wid31">
							<div class="profile_icon"></div>
							<div class="paddtop7">Profile</div>
						</div>
						</a>
					</li>
					<li>
						<a href="#" title="Inbox">
						<div class="wid31">
							<div class="inbox_icon"></div>
							<div class="paddtop7">Inbox</div>
						</div>
						</a>
					</li>
					<li>
						<a href="#" title="People" class="current">
						<div class="wid31">
							<div class="people_icon"></div>
							<div class="paddtop7">People</div>
						</div>
						</a>
					</li>
				</ul>
			</div>
			
		
		</div>
	
	</div>
	

</div>
<?php echo $this->layout()->content ?>
</body>
</html>