<div id="wid1000Auto">
	<!--<div id="header-wrapper">
		<div id="logo"><a href="#" title="Goo2o"><img src="images/logo_blue.gif" alt="logo" /></a></div>
        <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>
    </div>-->
   <form name="resetpasswordform" action="/secure/login/resetpassword/passcode/<?=$this->vcodes;?>/emailpasscode/<?=$this->passemailcode;?>" method="post" id="resettpasswordform">
    <div class="blueMainHeadingContainer">
    	<div class="blueMainHeading floatLeft">Change your Goo2o password</div>
        <div class="floatRight"><span class="content-text12">Already registered?</span> <a href="<?php echo HTTP_SECURE.'/login'; ?>" title="Sign in" class="hyperLinkBlue12">Sign in</a></div>
  	</div>
    <div class="lh60">&nbsp;</div>
    <div class="clearBoth">
    	<div class="wid255AlignR content-text12Lh20">New password</div>
        <div class="wid23AlignC content-text12Lh20">:</div>
        <div class="floatLeft"><input type="password" name="newpassword" class="input-textField230" id="password" onfocus="document.getElementById('show_hide_user_password').style.display='none'"/></div>
        <div class="suggestive-container floatLeft" id="show_hide_user_password" style="display:none">
                            	<div class="floatLeft"><img src="/images/secure/registration/suggestive-left-arrow.gif" alt="Left arrow" /></div>
                                <div class="suggestive-textContainer" id="error_user_password"></div>
                                <div class="floatLeft"><img src="/images/secure/registration/suggestive-right-curve.gif" alt="Right curve" /></div>
        </div>
             
    </div>
    <div class="lh10">&nbsp;</div>
      <div class="clearBoth">
    	<div class="wid255AlignR content-text12Lh20">Confirm password</div>
        <div class="wid23AlignC content-text12Lh20">:</div>
        <div class="floatLeft">
        	<div class="flaotLeft"><input type="password" name="newconfirmpassword" class="input-textField230" id="confirmpassword" onfocus="document.getElementById('show_hide_user_confirmpass').style.display='none'"/></div>
                
            <div class="lh20">&nbsp;</div>
            <div class="floatLeft">
              <input type="hidden" name="hideresetpasscode" value="hiddenpasswordvalue">
              <input type="hidden" name="newvcode" value="<?php echo $this->vcodes; ?>">
              <input type="hidden" name="hideforgetpasscde" value="<?php echo $this->passemailcode; ?>">
              <input type="submit" class="passwordbutton" title="Change" id="resetbutton" name="notmyaccount"  value="" />
                <!--<input type="image" src="images/change_btn.gif" title="Change" class="cursor"/>-->
            </div>
        </div>
        <div class="suggestive-container floatLeft" id="show_hide_user_confirmpass" style="display:none">
                            	<div class="floatLeft"><img src="/images/secure/registration/suggestive-left-arrow.gif" alt="Left arrow" /></div>
                                <div class="suggestive-textContainer" id="error_user_confirmpass"></div>
                                <div class="floatLeft"><img src="/images/secure/registration/suggestive-right-curve.gif" alt="Right curve" /></div>
       </div>  
    </div>
   </form>
</div>
