<div id="wid1000Auto">
	<!--<div id="header-wrapper">
		<div id="logo"><a href="#" title="Goo2o"><img src="images/logo_blue.gif" alt="logo" /></a></div>
        <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>
    </div>-->
    <div class="blueMainHeadingContainer">
    	<div class="blueMainHeading floatLeft">Change your Goo2o password</div>
	  	<div class="floatRight"><span class="content-text12">Already registered? </span><a href="<?php echo HTTP_SECURE;?>/login" title="Sign in" class="hyperLinkBlue12">Sign in</a></div>
   	</div>
    <div class="lh60">&nbsp;</div>
    <div class="content-text14">Your password has been changed!</div>
    <div class="lh5">&nbsp;</div>
    <div class="grey-text12">Please be sure to memorize it or note in safe place.</div>
    <div class="lh75">&nbsp;</div>
    <div class="floatLeft">
       <!--<input type="image" src="images/proceed_to_your_account_btn.gif" title="Proceed to your account" class="cursor" />-->
        <a href="<?php if($this->userid=='') {echo HTTP_SECURE.'/login';} else{ echo HTTP_SERVER.'/myaccount'; }?>">
            <!--<input type="submit" class="resetpasswordbutton" title="Proceed to your account" id="notmyaccount" name="notmyaccount"  value="" />-->
            <img src="/images/secure/registration/proceed_to_your_account_btn.gif" class="resetpasswordbutton" title="Proceed to your account"/>
        </a>
    </div>
</div>
