<div id="wid1000Auto">
    <!--<div id="header-wrapper">
		<div id="logo"><a href="#" title="Goo2o"><img src="images/logo_blue.gif" alt="logo" /></a></div>
        <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>
    </div>-->
    <div class="blueMainHeadingContainer">
    	<div class="blueMainHeading floatLeft">Your email address has been removed!</div>
        <div class="floatRight content-text12">Already registered? <a href="<?php echo HTTP_SECURE;?>/accountsetting/logout" class="hyperLinkBlue12" title="Sign in">Sign in</a></div>
  	</div>

    <div class="clearBoth">
    	<div class="lh40">&nbsp;</div>
    	<div class="clearBoth content-text14">Your email <span class="content-textGreen18"><?php echo $this->useremailaddress;?></span> has been removed from the Goo2o account.</div>
        <div class="lh25">&nbsp;</div>
        <div class="clearBoth content-text14">You will no longer receive any notifications intended for this account.</div>
        <div class="lh210">&nbsp;</div>
       

    </div>
</div>
