 <form id="editusercontact" name="updatecontact" action="" method="post">
<table cellpadding="0" cellspacing="0" align="center" width="1000">
	<tr>
    	<!--Right panel starts from here-->
    	<td width="260" valign="top">
        	<div class="editBasicInfoRightPanel">
            	<div class="lh25">&nbsp;</div>
            	<div class="businessDetialsLeftPanel">
				
               <?php
			 		$request = Zend_Controller_Front::getInstance()->getRequest();
					$controllerName = $request->getControllerName();
					$actionName = $request->getActionName();
					$genObj = new General();
					//$controllerName = "Store";
					$abc = $genObj->displaySettingMenuNew($controllerName,$actionName);
					echo $abc;
				?>
               
            	</div>

            </div>
        </td>
        <!--Right panel ends from here-->
        <!--Left panel starts from here-->
         
        <td width="740" valign="top">
        	<div class="editBasicInfoLeftPanel">
                <div class="lh25">&nbsp;</div>
                <div class="clearBoth">
                	<div class="floatLeft">
                        <div class="floatLeft blueMainHeading">Account settings</div>
                        <div class="navArrow">&nbsp;</div>
                      <?php if($this->mobilephone!=''){ ?>  <div class="floatLeft content_text15Lh25"><b>Edit your mobile number</b></div> <?php } 
                       else { ?>  <div class="floatLeft content_text15Lh25"><b>Add your mobile number</b></div> <?php } ?>
                    </div>
                    <div class="floatRight">
                    	<div class="backArrow"></div>
                        <div class="floatLeft"><a href="<?php echo HTTP_SECURE.'/accountsetting'; ?>" class="hyperLinkBlue13" title="Back to account settings">Back to account settings</a></div>
                    </div>
                </div>
                <div class="lh25">&nbsp;</div>
              
                <div class="clearBoth">
                    <div class="content_text12Lh20 wid139"><b>Your mobile no. is</b></div>
                    <div class="floatLeft">
                        <input type="text" name="user_phone" maxlength="10" id="user_phone" onfocus="document.getElementById('show_hide_user_phone').style.display='none'" class="inputWid93" value="<?php echo $this->mobilephone ?>"/>
                         <div class="lh5">&nbsp;</div>
                          <div class="clearBoth errorMsg" id="show_hide_user_phone" style="display:none">
                                  <div class="" id="error_user_phone"></div>
                          </div>

                    </div>
                
                </div>
                 
                <div class="lh40">&nbsp;</div>
              	<div class="wid160">
                        <div class="floatLeft">
                            <!--<input type="image" class="cursor" src="/images/secure/accountsetting/save_changes.png" title="Save Changes" />-->
                            <input type="submit" class="editcontactAccountBtn" title="Save Changes" id="submit"  value="" name="submit" />
                        </div>
                        <input type="hidden" name="pageaction" value="editusercontact"/>
                        <div class="floatRight"><a href="<?php echo HTTP_SECURE.'/accountsetting'; ?>" class="hyperLinkBlue12Lh25" title="Cancel">Cancel</a></div>
                    </div>
               <div class="lh40">&nbsp;</div>

           </div>

        </td>
       
        <!--Left panel ends from here-->
    </tr>
</table>
  </form>

