<form action="javascript:void(0);" name="resetusernameform" method="post" id="resetusernameform">
<table cellpadding="0" cellspacing="0" align="center" width="1000">
	<tr>
    	<!--Right panel starts from here-->
    	<td width="260" valign="top">
        	<div class="editUserNameRightPanel">
            	<div class="lh25">&nbsp;</div>
            	<div class="businessDetialsLeftPanel">
					
               <?php
			 		$request = Zend_Controller_Front::getInstance()->getRequest();
					$controllerName = $request->getControllerName();
					$actionName = $request->getActionName();
					$genObj = new General();
					//$controllerName = "Store";
					$abc = $genObj->displaySettingMenuNew($controllerName,$actionName);
					echo $abc;
				?>
                
            	</div>
            </div>
        </td>
        <!--Right panel ends from here-->
        <!--Left panel starts from here-->
        <td width="740" valign="top">
        	<div class="editUserNameLeftPanel">
                <div class="lh25">&nbsp;</div>
                <div class="clearBoth">
                	<div class="floatLeft">
                            <div class="floatLeft blueMainHeading">Account settings</div>
                            <div class="navArrow">&nbsp;</div>
                            <div class="floatLeft content_text15Lh25"><b>Edit username</b></div>
                        </div>
                    <div class="floatRight">
                    	<div class="backArrow"></div>
                        <div class="floatLeft"><a href="<?php echo HTTP_SECURE.'/accountsetting'; ?>" class="hyperLinkBlue13" title="Back to account settings">Back to account settings</a></div>
                    </div>
                </div>
                <div class="lh25">&nbsp;</div>
                <div class="grey_text12">Here you can change your username for your Goo2o account. Please remember that you can only change your username for once.</div>
                <div class="lh40">&nbsp;</div>
                <div class="clearBoth">
                    <div class="wid139 content_text12Lh20"><b>User name</b></div>
                    <div class="floatLeft"><input type="text" maxlength="15" name="username" id="username" value="<?php echo $this->usernameprev; ?>" onfocus="document.getElementById('show_hide_username').style.display='none'" class="inputWid153"/>
                        <div class="lh5">&nbsp;</div>
                         <div class="clearBoth errorMsg" id="show_hide_username" style="display:none">
                            	
                                <div id="error_username"></div>
                                
                        </div>
                    	<div class="lh15">&nbsp;</div>
                    	<div class="borderSeprator">&nbsp;</div>
                        <div class="lh10">&nbsp;</div>
                        <div class="clearBoth content_text12"><b>To save the above changes, enter your password below:</b></div>
                        <div class="lh10">&nbsp;</div>
                        <div class="clearBoth">
                        <div class="wid68 grey_text12Lh20"><b>Password</b></div>
                           <div class="floatLeft"><input type="password" name="currentpassword" id="currentpassword" onfocus="document.getElementById('show_hide_user_currentpass').style.display='none'" class="inputWid153" />
                               <div class="lh5">&nbsp;</div>
                               <div class="clearBoth errorMsg" id="show_hide_user_currentpass" style="display:none">

                                <div id="error_user_currentpass"></div>

                            </div>
                           </div>
                           
                        </div>
                    </div>

                </div>


                <div class="lh55">&nbsp;</div>
              	<div class="wid160">
                        <div class="floatLeft"><input type="image" class="cursor" src="/images/secure/accountsetting/save_changes.png" title="Save Changes" /></div>
                        <div class="floatRight"><a href="<?php echo HTTP_SECURE.'/accountsetting'; ?>" class="hyperLinkBlue12Lh25" title="Cancel">Cancel</a></div>
                    </div>
               <div class="lh40">&nbsp;</div>

           </div>

        </td>
        <!--Left panel ends from here-->
    </tr>
</table>
</form>