<form name="resetpasswordform" action="" method="post" id="updatepasswordform">
<table cellpadding="0" cellspacing="0" align="center" width="1000">
	<tr>
    	<!--Left panel starts from here-->
    	<td width="260" valign="top">
        	<div class="editBasicInfoRightPanel">
            	<div class="lh25">&nbsp;</div>
            	<div class="businessDetialsLeftPanel">
					
               <?php
			 		$request = Zend_Controller_Front::getInstance()->getRequest();
					$controllerName = $request->getControllerName();
					$actionName = $request->getActionName();
					$genObj = new General();
					//$controllerName = "Store";
					$abc = $genObj->displaySettingMenuNew($controllerName,$actionName);
					echo $abc;
				?>
                
            	</div>

            </div>
        </td>
        <!--Left panel ends from here-->
        <!--Right panel starts from here-->
        <td width="740" valign="top">
        	<div class="editBasicInfoLeftPanel">
                <div class="lh25">&nbsp;</div>
                <div class="clearBoth">
                	<div class="floatLeft">
                        <div class="floatLeft blueMainHeading">Account settings</div>
                        <div class="navArrow">&nbsp;</div>
                        <div class="floatLeft content_text15Lh25"><b>Update password</b></div>
                    </div>
                    <div class="floatRight">
                    	<div class="backArrow"></div>
                        <div class="floatLeft"><a href="<?php echo HTTP_SECURE.'/accountsetting'; ?>" class="hyperLinkBlue13" title="Back to account settings">Back to account settings</a></div>
                    </div>
                </div>
                <div class="lh25">&nbsp;</div>
                <div class="clearBoth content_text12">
                    <div class="wid139 content_text12Lh20"><b>New Password</b></div>
                    <div class="floatLeft"><input type="password" name="password" id="password"  class="inputWid153" maxlength="15" onfocus="document.getElementById('show_hide_user_password').style.display='none'" value=""/>
                        <div class="lh5">&nbsp;</div>
                        <div class="clearBoth errorMsg" id="show_hide_user_password" style="display:none">

                                <div id="error_user_password"></div>

                    </div>
                    </div>
                    
               	</div>
                <div class="lh10">&nbsp;</div>
                <div class="clearBoth content_text12">
                    <div class="wid139 content_text12Lh20"><b>Confirm Password</b></div>
                    <div class="floatLeft">
                        <div class="floatLeft"><input type="password" name="newconfirmpassword" id="confirmpassword" maxlength="15" onfocus="document.getElementById('show_hide_user_confirmpass').style.display='none'" class="inputWid153" value=""/>
                            <div class="lh5">&nbsp;</div>
                        <div class="clearBoth errorMsg" id="show_hide_user_confirmpass" style="display:none">

                                <div  id="error_user_confirmpass"></div>

                        </div>
                        </div>
                        
                        <div class="lh15">&nbsp;</div>
                        <div class="borderSeprator">&nbsp;</div>
                        <div class="lh15">&nbsp;</div>
                        <div class="clearBoth content_text12"><b>To save the above changes, enter your password below:</b></div>
                        <div class="lh10">&nbsp;</div>
                        <div class="clearBoth">
                        	<div class="wid114 grey_text12Lh20"><b>Current Password</b></div>
                            <div class="floatLeft"><input type="password" maxlength="15" name="currentpassword" id="currentpassword" onfocus="document.getElementById('show_hide_user_currentpass').style.display='none'" class="inputWid153" value=""/>
                                <div class="lh5">&nbsp;</div>
                                <div class="clearBoth errorMsg" id="show_hide_user_currentpass" style="display:none">

                                <div  id="error_user_currentpass"></div>

                            </div>
                            </div>
                            
                        </div>
                  </div>
               	</div>
                <div class="lh40">&nbsp;</div>
                <div class="clearBoth content_text12">
                    <div class="wid160">
                        <div class="floatLeft">
                        <input type="submit" class="changepasswordBtn" title="Save Changes" id="submit"  value="" name="submit" />
                        </div>
                        <div class="floatRight"><a href="<?php echo HTTP_SECURE.'/accountsetting'; ?>" class="hyperLinkBlue12Lh25" title="Cancel">Cancel</a></div>
                    </div>
                    <div class="lh40">&nbsp;</div>
                </div>
            </div>
       	</td>
        <!--Right panel ends from here-->
    </tr>
</table>
</form>
