<table cellpadding="0" cellspacing="0" align="center" width="1000">
	<tr>
    	<!--Left panel starts from here-->
    	<td width="260" valign="top">
        	<div class="editBasicInfoRightPanel">
            	<div class="lh25">&nbsp;</div>
            	<div class="businessDetialsLeftPanel">
					
               <?php
			 		$request = Zend_Controller_Front::getInstance()->getRequest();
					$controllerName = $request->getControllerName();
					$actionName = $request->getActionName();
					$genObj = new General();
					//$controllerName = "Store";
					$abc = $genObj->displaySettingMenuNew($controllerName,$actionName);
					echo $abc;
				?>
                
            	</div>
            	
            </div>
        </td>
        <!--Left panel ends from here-->
        <!--Right panel starts from here-->
        <td width="740" valign="top">
        	<div class="editBasicInfoLeftPanel">
                <div class="lh25">&nbsp;</div>
                <div class="clearBoth">
                	<div class="floatLeft">
                        <div class="floatLeft blueMainHeading">Account settings</div>
                        <div class="navArrow">&nbsp;</div>
                        <div class="floatLeft content_text15Lh25"><b>Edit username</b></div>
                    </div>
                    <div class="floatRight">
                    	<div class="backArrow"></div>
                        <div class="floatLeft"><a href="<?php echo HTTP_SECURE.'/accountsetting'; ?>" class="hyperLinkBlue13" title="Back to account settings">Back to account settings</a></div>
                    </div>
                </div>
                <div class="lh25">&nbsp;</div>
                <div class="clearBoth content_text12">
                    <div class="wid145 content_text12Lh20"><b>Username</b></div>
                    <div class="floatLeft">
                    	<div class="clearBoth grey_text14">Your Username is <b><?php echo $_SESSION['USER']['userDetails'][0]['username'];?></b></div>
                        <div class="lh10">&nbsp;</div>
                        <div class="clearBoth grey_text12Lh20">You have already changed your username on <b><?php echo $this->userupdatedtime; ?></b></div>
                        <div class="clearBoth grey_text12Lh20">You can change your username only once.</div>
                    </div>
               	</div>
                <div class="lh10">&nbsp;</div>
                
                                
            </div>  
       	</td>
        <!--Right panel ends from here-->
    </tr>
</table>
