



	<div class="mainHeader">
		<div class="header" align="center"><a href="/" title="eshopbox"><img src="/images/secure/elogin/logo.png" alt="eshopbox" /></a></div>
		<div class="clearBoth">
			<div class="topBorder">&nbsp;</div>
			<div class="botGap">&nbsp;</div>
			<div align="center" class="verifyErrorMSG">Sorry, we couldn't verify your email.</div>
			<div class="loginContainer" align="center">
				<div id="loginBG" class="loginBG">
					<input id="login" name="email" type="text" class="loginInput" value="email address" />
					<div class="errorMSG">This field is mandatory.</div>
				</div>				
			</div>
			<div class="submitBtnGap">&nbsp;</div>
			<div class="submitBTN">
				<div class="forgotpass"><a href="/secure/elogin" title="Back to login">Back to login</a></div>
				<div class="floatRight"><input type="image" src="/images/secure/elogin/submitBtn.png" width="90" height="32" title="Submit" alt="Submit" id="fofPassword" /></div>
			</div>
			<div class="submitBtnBotGap">&nbsp;</div>
			<div class="botBorder">&nbsp;</div>
		</div>
	</div>
