<?php echo $this->cssHelper();  ?>

<?php echo $this->javascriptHelper();  ?>

<table cellpadding="0" cellspacing="0" border="0" width="960" align="center">

	<!--Body Start here-->

    <tr>

    	<td>

        	<table cellpadding="0" cellspacing="0" border="0">

            	<tr>

                	<td height="40">&nbsp;</td>

                </tr>

                <tr>

                	<td>

                    	<div class="clearBoth">

                        	<div class="clearBoth">

                                <div class="clearBoth">

                                    <div class="bodyLeftBlock">&nbsp;</div>

                                    <div class="bodyMidBlock">Buyers</div>

                                    <div class="bodyRightBlock">Sellers</div>

                                </div>

                                <div class="clearBoth">

                                    <div class="bodyLeftBlock1"><div class="cartImage">&nbsp;</div></div>

                                    <div class="bodyMidBlock1">

                                        <div class="tickimages">&nbsp;</div>

                                        <div class="floatRight">purchase from goo2o verified merchant stores with confidence</div>

                                    </div>

                                    <div class="bodyRightBlock1">

                                        <div class="tickimages">&nbsp;</div>

                                        <div class="floatRight">setup your online store with goo2o merchant solution (GMS). <a href="http://www.goingo2o.com" target="_blank" title="learn more">learn more</a></div>

                                    </div>

                                </div>

                                <div class="clearBoth">

                                    <div class="bodyLeftBlock1"><div class="safeImage">&nbsp;</div></div>

                                    <div class="bodyMidBlock1">

                                        <div class="tickimages">&nbsp;</div>

                                        <div class="floatRight">safe shopping with complete purchase protection.</div>

                                    </div>

                                    <div class="bodyRightBlock1">

                                        <div class="tickimages">&nbsp;</div>

                                        <div class="floatRight">protection from chargebacks & online frauds.</div>

                                    </div>

                                </div>

                                <div class="clearBoth">

                                    <div class="bodyLeftBlock2"><div class="realTimeImage">&nbsp;</div></div>

                                    <div class="bodyMidBlock2">

                                        <div class="tickimages">&nbsp;</div>

                                        <div class="floatRight">real-time conversation with sellers throughout the buying process</div>

                                    </div>

                                    <div class="bodyRightBlock2">

                                        <div class="tickimages">&nbsp;</div>

                                        <div class="floatRight">chat, notify & update buyers to maximize their shopping experience</div>

                                    </div>

                                </div>

                            </div>

                            <div class="lh80">&nbsp;</div>

                            <div class="clearBoth">

                            	<div class="floatLeft"><a href="<?php echo HTTP_SECURE; ?>/registration" class="goo2oidBtn" title="create Goo2o ID"></a></div>

                                <div class="goo2oidBtncontent">A Goo2o ID is a user name you can use for everything you do on Goo2o platform. It lets you buy & sell safely with all your information stored at one place. Its absolutely free to create your own Goo2o ID.  </div>

                            </div>

                            <div class="footerGap">&nbsp;</div>

                        </div>

                        

                    </td>                	

                </tr>

            </table>

        </td>

    </tr>

    <!--Body End here-->

    <!--footer Start here-->

    <tr>

    	<td style="border-top:1px solid #b0b0b0;">

        	<div class="footerBlock">

            	<div class="footerleftBlock">

                	<ul>

                    	<li class="heading">Goo2o</li>

                        <li><a href="<?php echo HTTP_SERVER; ?>" title="Home">Home</a></li>

                        <li><a href="<?php echo HTTP_SECURE; ?>/login" title="Sign in">Sign in</a></li>

                        <li><a href="<?php echo HTTP_SECURE; ?>/registration" title="Create Goo2o id">Create Goo2o id</a></li>

                        <li><a href="<?php echo HTTP_SERVER; ?>/cart/#list" title="My cart">My cart</a></li>

                        <li><a href="<?php echo HTTP_SERVER; ?>/myaccount" title="My account">My account</a></li>

                    </ul>

                </div>

                <div class="footerleftBlock">

                	<ul>

                    	<li class="heading">About us</li>

                        <li><a href="http://www.goo2o.com/about" target="_blank" title="About">About</a></li>

                        <li><a href="http://www.goo2o.com/company" target="_blank" title="Company">Company</a></li>

                        <li><a href="http://www.goo2o.com/network" target="_blank" title="Network">Network</a></li>

                        <li><a href="http://www.goo2o.com/jobs" target="_blank" title="Jobs">Jobs</a></li>

                        <li><a href="http://www.goo2o.com/partners" target="_blank" title="Partners">Partners</a></li>

                    </ul>

                </div>

                <div class="footerleftBlock">

                	<ul>

                    	<li class="heading">Support</li>

                        <li><a href="http://support.goo2o.com/" title="Help center" target="_blank">Help center</a></li>

                        <li><a href="<?php echo HTTP_SERVER; ?>/myaccount/buyer/#purchase-listing" title="Track my order">Track my order</a></li>

                        <li><a href="http://www.goo2o.com/contact" target="_blank" title="Contact us">Contact us</a></li>

                        <li><a href="http://wiki.goingo2o.com" target="_blank" title="GMS support center">GMS support center</a></li>

                    </ul>

                </div>

                <div class="footerleftBlock">

                	<ul>

                    	<li class="heading">Legal</li>

                        <li><a href="http://support.goo2o.com/entries/507111-terms-conditions" title="Terms" target="_blank">Terms</a></li>

                        <li><a href="http://support.goo2o.com/entries/507112-privacy-policy" title="Privacy" target="_blank">Privacy</a></li>

                        <li><a href="http://support.goo2o.com/entries/507115-copyright-trademark-policy" title="Copyright" target="_blank">Copyright</a></li>

                    </ul>

                </div>

                <div class="footerRightBlock">

                	<div class="clearBoth">Copyright &copy; 2011-2012 Goo2o Technologies (P) Ltd.</div>

                    <div class="rightreserved">All Rights Reserved.</div>

                    <div class="trademark">Designated trademarks and brands are the<br />property of their respective owners.</div>

                </div>

            </div>

        </td>

    </tr>

    <tr>

    	<td height="35">&nbsp;</td>

    </tr>

    <!--footer End here-->

</table>