

	<div class="mainHeader">
		<div class="header" align="center"><a href="/" title="eshopbox"><img src="/images/secure/elogin/logo.png" alt="eshopbox" /></a></div>
		<div class="clearBoth">
			<div class="topBorder">&nbsp;</div>
			<div class="botGap">&nbsp;</div>
			<div class="loginContainer" align="center">
				<div id="newpassBG" class="newpassBG">
					<input id="newpass" type="text" class="loginInput" value="New password" />
					<input id="newpass1" type="password" class="loginInput" value="" />					
					<div class="errorMSG">Your password must contain atleast 6 characters.</div>
				</div>
				<div id="confpassBG" class="confpassBG">
					<input id="password" type="text" class="loginInput" value="Confirm password" />
					<input id="password1" type="password" class="loginInput" value="" />
					<div class="errorMSG">Your passwords didn't match.</div>
				</div>
			</div>
			<div class="loginBTN">
				<div class="floatRight"><input type="image" src="/images/secure/elogin/submitBtn.png" width="90" height="32" title="Submit" alt="Submit" id="resetpass" /></div>
			</div>
			<div class="botGap">&nbsp;</div>
			<div class="botBorder">&nbsp;</div>			
		</div>
	</div>
