<div class="mainCont690">
	<div class="logo"><a href="<?php echo HTTP_SERVER;?>"><img src="/images/default/error/goo2o_logo.jpg" alt="Goo2o" title="Goo2o"/></a></div>
	<div class="clear"></div>
	<h5>Sorry!! Your browser is not supported</h5>
	<p class="text">Goo2ostore uses features that are currently unavailable in this browser. So, we recommend you to view this website using one of the following browsers:</p>
	<div class="browserImg">
		<img src="/images/default/error/mozila.png" alt="Firefox"  title="Firefox" />
		<img src="/images/default/error/crome.png" alt="Chrome"  title="Chrome"/>
		<img src="/images/default/error/ie.png" alt="Internet Explorer"  title="Internet Explorer"/>
		<img src="/images/default/error/safari.png" alt="Safari"  title="Safari" />
		<img src="/images/default/error/opera.png" class="marRight" alt="Opera"  title="Opera"/>
		<div class="clear"></div>
	</div>
	<p><a href="<?php echo 'http://'.$_SESSION['redirectpage'];?>" class="continueLink" title="I still want to continue with my current browser.">I still want to continue with my current browser.</a></p>
</div>

