

<div class="mainCont690">


	<div class="logo"><a href="<?php echo HTTP_SERVER?>"><img src="/images/default/error/goo2o_logo.jpg" alt="Goo2o" title="Goo2o" /></a></div>

	<div class="clear"></div>

	<h5>Enable Javascript</h5>

	

	<div class="listPoints">

		<p>We are unable to load some features on this page due to one of the following reasons:</p>

		<ul>

			<li>JavaScript is disabled on the browser.</li>

			<li>JavaScript is not supported on the browser.</li>

		</ul>

		<p class="text">To view all the features, please enable JavaScript on this browser or upgrade to a JavaScript supported browser.</p>

		<p><a href="http://support.google.com/bin/answer.py?hl=en&answer=23852" class="continueLink" title="Learn more on how to enable JavaScript in your browser.">Learn more on how to enable JavaScript in your browser.</a></p>

	</div>

	<div class="jsErrImg"><img src="/images/default/error/js_error_img.png" /></div>

</div>

