<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Weldone</title>
<link href="/css/checkout/checkout.css" type="text/css" rel="stylesheet" media="screen" />
</head>

<body>
	<div class="makepurchase">
		<div class="chechoutHeadingMain">
			<div align="center" class="logostyle">A one Music & Computers</div>
			<div class="userstyle">Hi, <strong>Prateek Dimri</strong></div>
			<div class="chechoutHeading">Secure Checkout</div>
			<div class="chechoutHeadingBorder"></div>
		</div>
		<div class="chechoutBodyMain">
			<div class="thnxmsg">
				Thanks for Shopping with us.<br /><br />
				<span>You have purchase <strong>3 items</strong> worth <strong>Rs. 10000</strong>. Please note down Order Id <strong>OR-317-110-112</strong> for future reference.</span>
			</div>
			<div>
				<div class="leftBlockweldone">
					<div class="ordersummary">
						<div class="orderBlock">
							<div class="heading">Cart Summary</div>
							<div class="shadowborder">&nbsp;</div>
							<div>
								<div class="lh15">&nbsp;</div>
								<div class="clear">
									<div class="orderlabel">Order ID</div>
									<div class="ordervalue">:&nbsp;OR-317-110-112</div>
								</div>
								<div class="lh15">&nbsp;</div>
								<div class="clear">
									<div class="orderlabel">Order Date</div>
									<div class="ordervalue">:&nbsp;21/08/2012</div>
								</div>
								<div class="lh15">&nbsp;</div>
								<div class="clear">
									<div class="orderlabel">Payment Method</div>
									<div class="ordervalue">:&nbsp;Online Payment</div>
								</div>
								<div class="lh15">&nbsp;</div>
								<div class="clear">
									<div class="orderlabel">Order Amount</div>
									<div class="ordervalue">:&nbsp;Rs. 10000</div>
								</div>
							</div>
						</div>
						<div class="ShipmentBlock">
							<div class="heading">Shipping To</div>
							<div class="shadowborder">&nbsp;</div>
							<div class="address">
								<strong>Prateek Dimri</strong><span>House no-56, Pelican group housing sociecty. sec-10A, Gurgaon, Haryana -110021    9999555522</span>
							</div>
						</div>
					</div>					
				</div>
				<div class="rightBlockweldone">
					<div class="needhelp">
						<div class="heading">Cart Summary</div>
						<div class="shadowborder">&nbsp;</div>
						<div>
							<div class="lh15">&nbsp;</div>
							<div class="clear">
								<div class="orderlabel">Call Us</div>
								<div class="ordervalue">:&nbsp;0124 2570870<br />&nbsp;&nbsp;08826020004</div>
							</div>
							<div class="lh15">&nbsp;</div>
							<div class="clear">
								<div class="orderlabel">Mail Us</div>
								<div class="ordervalue">:&nbsp;info@viamazzini.com</div>
							</div>
						</div>
					</div>					
				</div>
			</div>
			<div class="aknowledgement"><a href="#" title="View aknowledgement receipt">View aknowledgement receipt</a> for this order or <a href="#" title="view your purchases">view your purchases</a>.</div>
			<div class="lh50">&nbsp;</div>
		</div>
	</div>
</body>
</html>
