<style>
.processing_container{ width:580px; margin:auto; clear:both; margin-top:50px;}
.processing_content{ font-family:"Times New Roman", Times, serif; font-size:21px; color:#329bdd; font-weight:normal; line-height:30px;}
.logoBG { background-image:url(/images/secure/loadinggoo2oLogo.png); background-repeat:no-repeat; height:58px; width:164px; margin:auto;  margin-top:20px; margin-bottom:20px;}
.loadingpos { padding:45px 0 0 37px; }
</style>
<script type="text/javascript" src="/jscript/common/o2ojslib.js"></script>
<script>
o2o(document).ready(function()
{
o2o('#subform').submit();

});
</script>

<?php

	

	$Merchant_Id = "M_ana19018_19018" ;//This id(also User Id)  available at "Generate Working Key" of "Settings & Options" 
	$Amount = $this->totalpay;//your script should substitute the amount in the quotes provided here
	//$Amount =1;
	$Order_Id =  $this->oid ;//your script should substitute the order description in the quotes provided here
	$Redirect_Url = "http://secure.goo2ostore.com/cart/pgtrans" ;//your redirect URL where your customer will be redirected after authorisation from CCAvenue

	$WorkingKey = "5lev0req5ugwcnm87u"  ;//put in the 32 bit alphanumeric key in the quotes provided here.Please note that get this key ,login to your CCAvenue merchant account and visit the "Generate Working Key" section at the "Settings & Options" page. 
	$Checksum = getCheckSum($Merchant_Id,$Amount,$Order_Id ,$Redirect_Url,$WorkingKey);

	$billing_cust_name=$this->billingdetail['fullname'];
	$billing_cust_address=$this->billingdetail['address'];
	$billing_cust_state=$this->billingdetail['state_name'];
	$billing_cust_country="India";
	$billing_cust_tel=$this->billingdetail['phone'];
	$billing_cust_email=$this->useremail;
	$delivery_cust_name="";
	$delivery_cust_address="";
	$delivery_cust_state = "";
	$delivery_cust_country = "India";
	$delivery_cust_tel="";
	$delivery_cust_notes="";
	$Merchant_Param='0-'.$this->ak.'-'.$this->oid;
	$billing_city = $this->billingdetail['cityname'];
	$billing_zip = $this->billingdetail['zipcode'];
	$delivery_city = "";
	$delivery_zip = "";

?>
<div class="processing_container">
	
	<div class="processing_content">Your order is being processed.Please be with us for some more time.</div>
	
	<div class="logoBG">
		<div class="loadingpos"><img src="/images/secure/goo2oloading.gif" /></div>
	</div>
	<div class="processing_content" align="center">Do not refresh or navigate away from this page</div>
</div>

	<form method="post" action="https://www.ccavenue.com/shopzone/cc_details.jsp" id="subform">
	<input type=hidden name=Merchant_Id value="<?php echo $Merchant_Id; ?>">
	<input type=hidden name=Amount value="<?php echo $Amount; ?>">
	<input type=hidden name=Order_Id value="<?php echo $Order_Id; ?>">
	<input type=hidden name=Redirect_Url value="<?php echo $Redirect_Url; ?>">
	<input type=hidden name=Checksum value="<?php echo $Checksum; ?>">
	<input type="hidden" name="billing_cust_name" value="<?php echo $billing_cust_name; ?>"> 
	<input type="hidden" name="billing_cust_address" value="<?php echo stripslashes($billing_cust_address); ?>"> 
	<input type="hidden" name="billing_cust_country" value="<?php echo $billing_cust_country; ?>"> 
	<input type="hidden" name="billing_cust_state" value="<?php echo $billing_cust_state; ?>"> 
	<input type="hidden" name="billing_zip" value="<?php echo $billing_zip; ?>"> 
	<input type="hidden" name="billing_cust_tel" value="<?php echo $billing_cust_tel; ?>"> 
	<input type="hidden" name="billing_cust_email" value="<?php echo $billing_cust_email; ?>"> 
	<input type="hidden" name="delivery_cust_name" value="<?php echo $delivery_cust_name; ?>"> 
	<input type="hidden" name="delivery_cust_address" value="<?php echo $delivery_cust_address; ?>"> 
	<input type="hidden" name="delivery_cust_country" value="<?php echo $delivery_cust_country; ?>"> 
	<input type="hidden" name="delivery_cust_state" value="<?php echo $delivery_cust_state; ?>"> 
	<input type="hidden" name="delivery_cust_tel" value="<?php echo $delivery_cust_tel; ?>"> 
	<input type="hidden" name="delivery_cust_notes" value="<?php echo $delivery_cust_notes; ?>"> 
	<input type="hidden" name="Merchant_Param" value="<?php echo $Merchant_Param; ?>"> 
	<input type="hidden" name="billing_cust_city" value="<?php echo $billing_city; ?>"> 
	<input type="hidden" name="billing_zip_code" value="<?php echo $billing_zip; ?>"> 
	<input type="hidden" name="delivery_cust_city" value="<?php echo $delivery_city; ?>"> 
	<input type="hidden" name="delivery_zip_code" value="<?php echo $delivery_zip; ?>"> 
	<INPUT TYPE="submit" value="submit" style="display:none;">
	</form>
