<div id="headerContainer">
    <div class="logoPosition"><a href="#" class="logo_header" title="Go o2o">&nbsp;</a></div>
    <div class="headerRightBlock">
        <div class="headerTop">
            <div class="headerTopGap">&nbsp;</div>
            <div class="clearBoth">
                <div class="floatLeft">
                    <div class="floatLeft">
                        <a href="/people" class="headerNav" title="Explore">
                            <span class="navExplorer"></span>
                            Explore
                        </a>
                    </div>
                    <div class="headerNavGap">&nbsp;</div>
                    <div class="floatLeft">
                        <a href="#" class="headerNav" title="Profile">
                            <span class="navProfile"></span>
                            Profile
                        </a>
                    </div>
                    <div class="headerNavGap">&nbsp;</div>
                    <div class="floatLeft">
                        <a href="#" class="headerNav" title="Inbox">
                            <span class="navInbox"></span>
                            Inbox
                        </a>
                    </div>
                    <div class="headerNavGap">&nbsp;</div>
                    <div class="floatLeft">
                        <a href="#" class="headerNav" title="Manage">
                            <span class="navManage"></span>
                            Manage
                        </a>
                    </div>
                </div>
                <div class="headerRightNav">
                    <div class="floatLeft"><a href="#" class="headerNav" title="Buy">Buy</a></div>
                    <div class="floatLeft">&nbsp;&nbsp;|&nbsp;&nbsp;</div>
                    <div class="floatLeft"><a href="#" class="headerNav" title="Sell">Sell</a></div>
                    <div class="floatLeft">&nbsp;&nbsp;|&nbsp;&nbsp;</div>
                    <div class="floatLeft"><a href="#" class="headerNav" title="Settings">Settings</a></div>
                    <div class="floatLeft">&nbsp;&nbsp;|&nbsp;&nbsp;</div>
                    <div class="floatLeft"><a href="#" class="headerNav" title="Help">Help</a></div>
                    <div class="floatLeft">&nbsp;&nbsp;|&nbsp;&nbsp;</div>
                    <div class="floatLeft"><a href="#" class="headerNav" title="Sign out">Sign out</a></div>
                </div>
            </div>
        </div>
        <div class="headerBot">
            <div class="browseDept">
                <div class="browDeptTxt">
                    <div class="floatLeft">Browse Departments</div>
                    <div class="floatLeft" style="margin:14px 0 0 7px;"><img src="/images/default/downarrow.png" border="0" /></div>
                </div>
                <div class="headerBotSep">&nbsp;</div>
                <div class="searchContainer">
                    <div class="searchTopGap">&nbsp;</div>
                    <div class="headerSearchBox"><input type="text" name="" id="" class="inputSearchBox" value="Who are you looking for?" onfocus="if(this.value == this.defaultValue) this.value = '';" onblur="if(this.value == '') this.value = this.defaultValue;" /></div>
                    <div class="searchBtn"><input type="image" src="/images/default/search_btn.png" title="Search" /></div>
                </div>
            </div>
            <div class="headerBotSep">&nbsp;</div>
            <div class="floatLeft">
                <div class="myaccTop">&nbsp;</div>
                <div class="myacctxt"><a href="#" class="headerNavBlack" title="My Account">My Account</a></div>
            </div>
            <div class="headerBotSep">&nbsp;</div>
            <div class="myacctxt">
                <div class="myaccTop">&nbsp;</div>
                <div class="clearBoth">
                    <a href="#" class="headerNavBlack" title="0 items">
                        <span class="navMyCart"></span>
                        (0)
                    </a>
                </div>
            </div>
        </div>
        <div class="headerBotBorder">&nbsp;</div>
    </div>
	<div class="headerGapBot">&nbsp;</div>
</div>
