<!--<div class="startHeaderCont">
	<div class="logo"><a href=" <?php echo HTTP_SERVER; ?>/myaccount" title="Goo2o"><img src="/images/secure/demo/goo2ologo.png" /></a></div>
	<div class="processingImg"><div class="createStore"></div></div>
</div>-->


<table width="1000" align="center" cellpadding="0" cellspacing="0" border="0">
	<tr>
		<td>
			<div class="clearBoth startHeaderCont">
			<div class="clearBoth">
				<div class="logo"><a href=" <?php echo HTTP_SERVER; ?>/myaccount" class="cursor_pointer" title="Goo2o" alt="Goo2o"><img src="/images/secure/merchantenrollment/logo_blue.gif" alt="logo" /></a>
				
				</div>
				<div class="processingImg"><div class="createStore"></div></div>
			</div>
				<!--<div class="floatRight">
					<div class="lh10">&nbsp;</div>
				</div>-->
			</div>
		</td>
	</tr>
	<!--<tr>
		<td height="14"></td>
	</tr>
	<tr>
		<td><div class="solidBorder">&nbsp;</div></td>
	</tr>
	<tr>
		<td height="18"></td>
	</tr>-->
</table>