<div id="enrollment-header">
    <div id="header-wrapper">
            <div id="logo"><a href="javascript:void(0)" title="Goo2o" class="floatLeft"><img src="/images/secure/merchantenrollment/logo_blue.gif" alt="logo" /></a><span class="logo_punchline flaotLeft">Goo2o merchant solution</span></div>
            <div class="header-rightText"><div class="<?php echo $this->action_class;?>"></div></div>
    </div>
</div>