<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<link rel="shortcut icon" href="http://login.eshopbox.com/images/favicon.ico" />
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<?php echo $this->headMeta() ?>
		<?php echo $this->headTitle() ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript();?>
		
	</head>

	<body>
		
		<?php   echo $this->layout()->content ?>
	</body>
</html>



