<?php

	$page_url = basename($_SERVER['PHP_SELF'],'/');

	$page_url = substr($page_url, 0, -4);

?>

<div id="headerContainer" >

   

    <div class="container">
<?php if($this->controller!='error'){?>
        <div class="floatLeft logoTopGap">

            <a href="#" title="Go o2o Logo"><img src="/images/secure/goo2o_logo.png" border="0" title="Goo2o" /></a>

        </div>
		<?php } ?>

        <div class="floatRight checkOutSteps">

        <?php if($this->request['action'] == 'set-gift-configure'){?>

        	<div class="progressbar_step2"></div> 

         <?php }else if($this->request['action'] == 'review-and-confirm-gift'){ ?>

         	<div class="progressbar_step3"></div> 

         <?php }else if($this->request['action'] == 'well-done'){?>

		 	<div class="progressbar_step4"></div> 

		 <?php }else {?>

			<div class="checkoutBar">&nbsp;</div>

		<?php }?>

        </div>

    </div>

    <?php if($this->controller!='error'){?><div class="lh13">&nbsp;</div><?php } ?>

    <div class="container">

        

        <div class="headerLine"></div>

    </div>

</div>

<div class="mainGap">&nbsp;</div>





