<?php if($this->controller!='o2ologin'){ 

?>
<?php if($_GET['tab']=='' && $_SESSION['mypage']==''){ ?>

<div class="headContainer" >

  <div id="header-wrapper">

    <div id="logo"><a href="<?php echo HTTPS_SERVER;?>" title="Goo2o"><img src="/images/default/logo.png" alt="Goo2o" /></a></div>

    <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>

  </div>

</div>

<?php } else if($_GET['tab']==2){ ?>

<div class="headContainer" >

  <div id="header-wrapper">

    <div>

      <div id="logo"><a href="<?php echo HTTP_SERVER;?>" title="Goo2o"><img src="/images/secure/goo2ologo.png" alt="Goo2o" /></a> </div>

      <span class="floatLeft" style="margin-top:36px; margin-left:14px;font-size:18px; font-weight:normal; font-family:verdana; color:#0083cb;">Goo2o merchant solution</span> </div>

    <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>

  </div>

</div>

<?php }	else if($_SESSION['mypage']=='http://secure.goo2ostore.com/demo/create-my-free-demo-store'){ ?>

	 <div class="clearBoth startHeaderCont">

		<div class="floatLeft"><a href=" <?php echo HTTP_SERVER; ?>/myaccount" class="cursor_pointer" title="Goo2o" alt="Goo2o"><img src="/images/secure/merchantenrollment/logo_blue.gif" alt="logo" /></a>

		</div>

		<div class="processingImg"><div class="signIn"></div></div>

		<div class="floatRight">

			<div class="lh10">&nbsp;</div>

		</div>

	</div>

<?php }
else{?>

<div class="headContainer" >

  <div id="header-wrapper">

    <div id="logo"><a href="<?php echo HTTPS_SERVER;?>" title="Goo2o"><img src="/images/default/logo.png" alt="Goo2o" /></a></div>

    <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>

  </div>

</div>
<?php }
} else {?>

<div class="headContainer" style="width:600px;" >

  <div id="header-wrapper">

    <div id="logo" style="margin: 32px 20px 0;"><a href="javascript:void(0)" title="Goo2o"><img src="/images/secure/goo2o_logo.png" alt="Goo2o" /></a></div>

    <div class="header-rightText" style="font-size: 16px;">Goo2o helps you buy & sell live with real-time conversation.</div>

  </div>

</div>

<?php } ?>

