<?php 
if($_GET['get']==1)
{
	echo "<pre>";
	print_r($_SESSION);	
}
	$request = Zend_Controller_Front::getInstance()->getRequest();
	$controllerName = $request->getControllerName();
	$moduleName = $request->getModuleName();
         $orilogin = new Zend_Session_Namespace('original_login');
       // echo $orilogin->user['0']['vcode'];exit;
	$genObj = new General();
	$getMallsById=$genObj->getApiDetails($_SESSION['USER']['userDetails'][0]['user_email_address']);
	$CLASS= $genObj->getHeaderButtonClass($controllerName ,$actionName);
       // echo $orilogin->user['0']['vcode'];exit;
$userstatus=$genObj->checkuserverification($orilogin->user['0']['vcode']);

$userName = new Zend_Session_Namespace('USER');
$this->mapper = new Default_Model_InboxMapper();
if($_SESSION['USER']['userDetails'][0]['user_email_address']!='')  
$unreadMessage=$this->mapper->getUnreadmessage();
$totalmessage=  $unreadMessage['total'];
//print_r($userName->stores);
$loginrole=$userName->stores['0']['role'];
if($loginrole==NULL){
$storemanagementlink=HTTPS_SECURE.'/merchantenrollment/business-details';
$createstorelink=CREATE_STORE;//'Welcome to Goo2o';
$title=CREATE_STORE;//$createstorelink;
$mainlink='<a href="'.$storemanagementlink.'" title="'.$getMallsById[0]['title'].'"><span>&nbsp;</span><div class="floatLeft">'.$createstorelink.'</div></a>';
//$mainlink='<a href="'.$storemanagementlink.'" title="'.$getMallsById[0]['title'].'"><span>&nbsp;</span>'.$createstorelink.'</a>';
//$mainlink=$createstorelink;
} else {
$storemanagementlink=HTTP_SERVER."/admin/index/change-profile/a/".$getMallsById[0]['apikey']."/u/".$getMallsById[0]['user_id'];
$createstorelink=STORE_MANAGEMENT;
$title=$getMallsById[0]['title'];
$mainlink='<a href="'.$storemanagementlink.'" title="'.$getMallsById[0]['title'].'"><span>&nbsp;</span><div class="floatLeft">'.$createstorelink.'</div></a>';
}
$cartSession = new Zend_Session_Namespace('Api_Model_Cart');
$carttotal=count($cartSession->items);
?>
<div id="HeaderContainer" class="HeaderContainer">
	<!--<div class="headerTopWelcomeMSGBlockContainer">
		<div class="headerTopWelcomeMSGBlock">
        	<div class="msgTxt">
            	<strong>Welcome back!</strong> If you didn't mean to reactivate your account, you can deactivate it again from the <a href="#" title="account settings page">account settings page.</a>
            </div>
            <div class="mstTxtBelow">
            	<a href="#" title="Close"><div class="closeIcon"></div> <strong>Close</strong></a>
            </div>
        </div>
    </div>-->
    <?php if($userstatus){ ?>
    <script >
		 function resendurl(url)
		 {
		 	window.location.href=url+'?return='+encodeURIComponent(window.location);		
		 }
	</script>
    <input type="hidden" name="userstatus" id="userstatus" value="<?php echo $userstatus;?>" />
    <input type="hidden" name="floatmenuexceeds" id="floatmenuexceeds" value="55" />
    <div id="msgblock2" class="headerTopMSGBlockContainer">
		<div class="headerTopMSGBlock">
        	<div class="msgTxt">
            	<strong>Verify your email address to continue access to your Goo2o account.</strong>&nbsp;&nbsp;
            	A verification message was sent to <strong><?php echo($orilogin->user['0']['user_email_address']);?></strong><br />
                <div class="floatLeft"><a onclick="resendurl('<?php echo HTTPS_SECURE.'/registration/resendconfirmation/passcode/'.$orilogin->user['0']['vcode']; ?>')" href="javascript:void(0)" title="Resend confirmation">Resend confirmation </a></div>
                <div class="bullet">&nbsp;</div>
                <div class="floatLeft"><a href="<?php echo HTTPS_SECURE.'/accountsetting/editemail'; ?>" title="Update email address">Update email address</a></div>
            </div>            
        </div>
    </div>
    <?php } ?>
    <div class="headerTopBlockContainer">
		<div class="headerTopBlock">
        	<div class="storMGTBlock">
            	 <div class="ChangeClass <?php echo $managementClass; ?>"><?php echo $mainlink;?></div>            
            </div>
            <?php if($_SESSION['original_login']['user'][0]['store_owner_type'] == '1'){?>
            	<div class="upgradeBtn"><a href=" <?php echo HTTP_SECURE; ?>/merchantenrollment/business-details"><span>&nbsp;</span></a></div>
            <?php } ?> 
            <div class="inAccBlock">
                <div class="inboxAccBlockTxt">
                	<div class="inbaccclass <?php echo($controllerName=='inbox')?'selectedheader':''; ?>">
	                	<a href="<?php echo HTTP_SERVER;?>/inbox/#list" title="Inbox"><span><?php echo HEADER_INBOX;  ?></span><span class="inboxNotificationTops" ><?php echo (($totalmessage>0)?' ('.$totalmessage.')':'')?></span></a>
                    </div>
                </div>
                <div class="inAccBlockTxt">
                	<div class="accclass <?php echo($moduleName=='myaccount')?'selectedheader':''; ?>">
                		<a href="<?php echo HTTP_SERVER;?>/myaccount" title="My Account"><?php echo HEADER_ACCOUNT;  ?></a>
                	</div>
                </div>
            </div>
        </div>
    </div>
    <div class="headerMidBlockContainer">
    	<div class="headerMidBlock">
        	<div class="logoBlockHeader">
            	<div class="leftBlock"><a href="<?php echo HTTP_SERVER;?>" title="Goo2o.com"><img src="/images/admin/goo2ologosetting.png" alt="Goo2o" title="Goo2o" border="0" /></a></div>
                <div class="rightBlock">
                	<table cellpadding="0" cellspacing="0" border="0" align="right">
                    	<tr>
                        	<td class="topNav">
                            	<strong>Hi, <?php echo $orilogin->user['0']['user_full_name']; ?></strong>&nbsp;&nbsp;|&nbsp;
                                <a href="<?php echo HTTP_SERVER;?>/cart/#list" title="My Cart <?php echo  (($carttotal>0)?'('.$carttotal.')':'')?>">My Cart <?php echo  (($carttotal>0)?'('.$carttotal.')':'')?></a>&nbsp;&nbsp;|&nbsp;
                                <a href="<?php echo HTTPS_SECURE;?>/accountsetting" title="Settings" class="
								<?php 
									//echo($controllerName=='accountsetting')?'selectheaderrighttab':'';
									if(($controllerName=='accountsetting')||($controllerName=='mypayment')||($moduleName=='settings')){
										echo 'selectheaderrighttab';
									}
								?>
								">Settings</a>&nbsp;&nbsp;|&nbsp;
                                <a href="http://support.goo2o.com" title="Help" target="_blank">Help</a>&nbsp;&nbsp;|&nbsp;
                                <a href="<?php echo HTTP_SERVER.'/admin/create/logout'?>" title="<?php echo USER_LOGOUT ; ?>"><?php echo USER_LOGOUT ; ?></a>
                            </td>
                        </tr>                        
                    </table>
                </div>
            </div>
        </div>
    </div>	
    <div class="headerBotBlockContainer">
    	<div class="headerBotBlock">
        	<?php if($loginrole!=NULL){
			if(($controllerName=='accountsetting')||($controllerName=='mypayment')){
										//echo 'selectheaderrighttab';
									} else {
			 ?>
            	<!--<div class="headerBotBlockLeftBlock">
                    <div <?php  //echo $menu;  ?> class="HTabBlock2 clearBoth">
                    <?php //echo $genObj->displayMenuNew($userName->stores['0']['mallurl']); ?>	
                    </div>                
            	</div>-->
                <div class="headerBotBlockLeftBlock">&nbsp;</div>
                <div <?php  echo $menu;  ?> class="headerBotBlockRightBlock">
                    <div class="innerDivStore">
                        <div class="container">
                            <!--<select class="inpSelect">
                                <option>Goo2o Store</option>
                                <option>Goo2o Store</option>
                                <option>Goo2o Store</option>
                            </select>-->
                            <?php 
                            if(!empty($getMallsById)) { echo '<select class="inpSelect o2ojsmallname" onchange="window.location.href=this.options[this.selectedIndex].value">';
                                foreach($getMallsById as $mall_key => $mall_value){
                                if($mall_value['store_apikey']==$userName->stores['0']['store_apikey']) 
                                    $selected=' selected';
                                else
                                    $selected='';
                                ?>
                                    <option <?php echo $selected;?> value="<?php echo HTTP_SERVER ?>/admin/index/change-profile/a/<?php echo $mall_value['apikey']?>/u/<?php echo $mall_value['user_id']?>"><?php echo $mall_value['title'];?></option>
                                <?php } 
                                echo '</select>';
                            }
                            ?>
                        </div>
                    </div>
                </div>
			<?php } }?>
        </div>
    </div>
</div>
<!-------------------header for Variation (End)-------------------->
<!--<div class="clearBoth new_dropDown">
    <div class="newdropDownLeft"></div>
    <div class="floatLeft">
        <ul>
            <li><a href="javascript:void(0)">Create a product</a></li>
            <li><a href="javascript:void(0)">Create category</a></li>
            <li><a href="javascript:void(0)" class="selected">Create variation group</a></li>
            <li><a href="javascript:void(0)">Create feature group</a></li>
            <li><a href="javascript:void(0)">Create customers</a></li>
        </ul>
    </div>
    <div class="newdropDownBottom"></div>
</div>-->
<div class="welldone_message_container" style="display:<?php echo ($this->displaytype == '') ? 'none' : $this->displaytype; ?>; top:0px; right:0px;  position:fixed; z-index:6565;" id="showhide">
    <div class="welldone_content" id="msgheader"><?php echo $this->data; ?></div>
</div>
<!------------------------------Yes no popup----->
<div id="closeboxcategory" style="display:none;">
    <table cellpadding="0" cellspacing="0" border="0" width="500" class="popup_border" >
        <tr>
            <td valign="top">
                <div class="popup_width">
                    <div class="popup_topbar">
                        <div class="floatLeft topbar_heading" id="popup_heading">Are you sure!</div>
                        <div class="floatRight closepadding" style="cursor:pointer;"><a class="cancel_link"><img src="/images/admin/popup_close.gif" alt="Close" title="Close" /></a></div>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td valign="top" height="20">&nbsp;</td>
        </tr>
        <tr>
            <td valign="top">
                <div class="wid445_popup">
                    <div class="floatLeft popup_text" id="popup_details_text">Any unsaved data will be lost.  Do you still want to quit the process?</div>
                    <div class="lh20">&nbsp;</div>
                    <div class="popup_underline"></div>
                    <div class="lh7">&nbsp;</div>
                    <div class="floatRight">
                        <div class="floatLeft curspointer"><input type="image" src="/images/addbrand/yes_btn.jpg" alt="Yes" title="Yes" id="saveandquit" class="saveandquit"/></div>
                        <div class="wid15">&nbsp;</div>
                        <div class="floatLeft curspointer"><input type="image" src="/images/addbrand/no_btn.jpg" alt="No" title="No" class="cancel_link"/></div>
                    </div>
                    <div class="lh20">&nbsp;</div>
                </div>
            </td>
        </tr>
        <tr>
            <td valign="top" height="25">&nbsp;</td>
        </tr>
    </table>
</div>
<div id="lightbox" style="display:none;">&nbsp;</div>
