<link rel="stylesheet" type="text/css" href="/css/default/customerdisputelisting.css"/>
<div id="request_listing_mainContainer">
	<div class="clearBoth">
        <div class="lh42">&nbsp;</div>
        <div class="floatLeft">
            <div class="contentBlueHeading">Disputes</div>
        </div>
        <div class="floatRight">
        	<div class="floatLeft">
        		<div class="rightSearchBoxBorder"><input type="text" class="rightSearchBoxInputText" /></div>
            </div>
			<div class="floatLeft"><a href="#" title="Search"><img src="/images/default/search_btn.png" /></a></div>        
        </div>
	</div>
    <div class="lh5">&nbsp;</div>
    <div class="borderBottom">&nbsp;</div>
    <!--content starts from here-->
    <div class="clearBoth">
    	<table cellpadding="0" cellspacing="0" border="0">
        	<tr>
            	<!--Left panel starts from here-->
            	<td valign="top">
                	<div class="left_panel">
                    	<div class="clearBoth listing_selectedBg">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22"><a href="/inbox/#customerdisputedetails">You have opened</a> a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" title="Shekhar Mishra" class="user_link">Shekhar Mishra</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">You have opened a dispute against Shekhar Mishra regarding an order item ID - 12525</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was described by a store owner</div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        <div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                        	<div class="floatLeft">
                            	<div class="floatLeft">
	                            	<div class="listingImgContainer"><img src="/images/default/msgers_img.png" alt="" /></div>
                              	</div>
                                <div class="floatLeft">
                                    <div class="clearBoth"><a href="#" class="user_link" title="Amit kumar">Amit kumar</a></div>
                                    <div class="lh5">&nbsp;</div>
                                    <div class="clearBoth content-text12Lh22">Amit Kumar has raised a dispute against you regarding an order item ID - 7645454</div>
                                    
                                    <div class="clearBoth contentItalicsText">I have received an item significantly different than what was delivered </div>
                                    <div class="lh10">&nbsp;</div>
                                    <div class="requestOpenedText">dispute raised</div>
                                 </div>
                            </div>
                            <div class="floatRight">
                            	<div class="lh28">&nbsp;</div>
                            	<div class="floatLeft requestOpenedText">a few seconds ago</div>	
                            	<div class="wid30">&nbsp;</div>
                            </div>
                            <div class="lh15">&nbsp;</div>
                            <div class="dividerLine">&nbsp;</div>
                        </div>
                        
                        <div class="lh37">&nbsp;</div>
                     </div>
                     <div class="clearBoth">
                     	<!-- Bottom page navigation starts here -->
       					<div class="floatRight">
                        	<div class="floatLeft">
                                <div class="floatLeft">
                                    <div class="assign_product_table_bottom_button"><a href="#" title="Prev" class="assign_product_table_bottomLink">Prev</a></div>
                                </div>
                                <div class="wid7">&nbsp;</div>
                                <div class="floatLeft">
                                    <div class="assign_product_table_bottom_buttonSelected"><a href="#" class="assign_product_table_bottomLinkSelected" title="1">1</a></div>
                                </div>
                                <div class="wid5">&nbsp;</div>
                                <div class="floatLeft">
                                    <div class="assign_product_table_bottom_button"><a href="#" title="2" class="assign_product_table_bottomLink">2</a></div>
                                </div>
                                <div class="wid5">&nbsp;</div>
                                 <div class="floatLeft">
                                    <div class="assign_product_table_bottom_button"><a href="#" title="3" class="assign_product_table_bottomLink">3</a></div>
                                </div>
                                <div class="wid10">&nbsp;</div>
                                <div class="floatLeft">
                                    <div class="assign_product_dotText">...</div>
                                </div>
                                <div class="wid10">&nbsp;</div>
                                 <div class="floatLeft">
                                    <div class="assign_product_table_bottom_button"><a href="#" title="27" class="assign_product_table_bottomLink">27</a></div>
                                </div>
                                <div class="wid5">&nbsp;</div>
                                <div class="floatLeft">
                                    <div class="assign_product_table_bottom_button"><a href="#" title="Next"class="assign_product_table_bottomLink">Next</a></div>
                                </div>
                          	</div>
                            <div class="wid25">&nbsp;</div>
                         </div>
       					<!-- Bottom page navigation ends here -->
                        <div class="lh25">&nbsp;</div>
                     </div>
                </td>
                <!--Left panel ends here-->
                <!--Seperator starts from here-->
                <td valign="top" bgcolor="#cdcdcd" width="1"></td>
                <!--Seperator ends here-->
                <!--Right panel starts from here-->
                <td valign="top">
                	<div class="right_panel">
                    	<div class="clearBoth">
                        	<div class="lh10">&nbsp;</div>
                            <div class="clearBoth">
                            	<div class=" wid20">&nbsp;</div>
                           		<div class="floatLeft"><input type="image" src="/images/default/start_a_new_conversation_btn.png" title="Start a new conversation" /></div>
                            </div>
                            <div class="lh7">&nbsp;</div>
                            <div class="clearBoth">
                            	<div class=" wid20">&nbsp;</div>
                           		<div class="floatLeft"><form action="open_a_dispute.php" method="post"><input type="image" src="/images/default/open_a_new_dispute_btn.png" title="Open a new dispute" /></form></div>
                            </div>
                            <div class="lh20">&nbsp;</div>
                            <div class="right_panel_links">
                            	<ul>
                                	<li><a href="#" title="All Messages">All Messages</a></li>
                                    <li><a href="#" title="Conversations">Conversations</a></li>
                                    <li><a href="#" title="Notifications">Notifications</a></li>
                                    <li><a href="#" title="Requests">Requests</a></li>
                                    <li class="selected">Disputes(1)</li>
                                </ul>
                            </div>
                         </div>
                    </div>
                </td>
                <!--Right panel ends here-->
            </tr>
        </table>
    </div>
    <!--content ends here-->
</div>