<script type="text/javascript">
jQuery(document).ready(function(){

window.setInterval(function() {
window.location.href="/freetrial/storeready";
}, 10000);


})


</script>
	
	
	<div class="mainHeader">
		<div class="header" align="center"><a href="#" title="eshopbox"><img src="/images/secure/elogin/logo1.png" alt="eshopbox" /></a></div>
		<div class="clearBoth">
			<div class="topBorder">&nbsp;</div>
			<div class="botGap">&nbsp;</div>
			<div class="loginContainer" align="center">
				<div class="heading">Please wait, we are creating your store..</div>
				<div class="chakriCont" align="center"><img src="/images/secure/elogin/chakri.png" /></div>
			</div>			
		</div>
	</div>