<div id="wid1000Auto">
	<!--<div id="header-wrapper">
		<div id="logo"><a href="#" title="Goo2o"><img src="images/logo_blue.gif" alt="logo" /></a></div>
        <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>
        </div>-->
    <div class="clearBoth">
    	<div class="blueMainHeadingContainer">
    		<div class="floatLeft blueMainHeading">Forgot your password?</div>
            <div class="floatRight content-text12">Already registered? <a href="/login" class="hyperLinkBlue12" title="Sign in">Sign in</a></div>
        </div>
        <div class="lh50">&nbsp;</div>
        <div class="wid687">
            <div class=" content-text14">OK, we’ve sent the link to reset your password on <strong><?php echo $this->useremailaddress; ?></strong>. Go check it.</div>

        </div>
        <div class="forgot_seperator">&nbsp;</div>
        <div class="wid252">
        	<div class="clearBoth grey-text12Lh20">You can keep this page open while you check your email. If you don’t receive the instructions within a minute or two</div>
            <div class="lh20">&nbsp;</div>
            <div class="clearBoth"><a href="<?php echo HTTPS_SECURE.'/login/forgetpasswordresendinstruction/passcode/'.$this->vcodes; ?>" title="Re-send instructions" class="hyperLinkBlue14">Re-send instructions</a></div>
       	</div>
    </div>

</div>
