
<div id="wid1000Auto">
	<!--<div id="header-wrapper">
		<div id="logo"><a href="#" title="Goo2o"><img src="images/logo_blue.gif" alt="logo" /></a></div>
        <div class="header-rightText">Goo2o helps you buy & sell live with real-time conversation.</div>
    </div>-->
     <form name="forgetpasswordform" action="/login/forgetpassword" method="post" id="forgetpasswordform">
    <div class="clearBoth">
    	<div class="blueMainHeadingContainer">
    		<div class="floatLeft blueMainHeading">Forgot your password?</div>
            <div class="floatRight content-text12">Already registered? <a href="/login" class="hyperLinkBlue12" title="Sign in">Sign in</a></div>
        </div>
        <div class="lh50">&nbsp;</div>
        <div class="wid687">
            <div class="clearBoth">
                <div class="wid141AlignR content-text12Lh20">Enter address/username</div>
                <div class="wid23AlignC content-text12Lh20">:</div>
                <div class="wid430">
                    <div class="floatLeft">
                        <input type="text" id="user_email_address" name="changeduseremail" class="input-textField230" value="<?php echo $this->useremailaddresses; ?>"/>
                    </div>
                     <div class="suggestive-container floatLeft" id="show_hide_user_email_address" style="display:none">
                            	<div class="floatLeft"><img src="/images/secure/registration/suggestive-left-arrow.gif" alt="Left arrow" /></div>
                                <div class="suggestive-textContainer" id="error_user_email_address"></div>
                                <div class="floatLeft"><img src="/images/secure/registration/suggestive-right-curve.gif" alt="Right curve" /></div>
                    </div>
             <?php if($this->emailExist){?>
             <div class="suggestive-container floatLeft" id="show_email_address" style="display:block">
                            	<div class="floatLeft"><img src="/images/secure/registration/suggestive-left-arrow.gif" alt="Left arrow" /></div>
                                <div class="suggestive-textContainer" id="error_address">We couldn’t found this address</div>
                                <div class="floatLeft"><img src="/images/secure/registration/suggestive-right-curve.gif" alt="Right curve" /></div>
            </div>
              <?php } ?>
                </div>
             </div>
            <div class="lh15">&nbsp;</div>
            <div class="clearBoth">
                <div class="wid141AlignR content-text12Lh20">Are you human?</div>
                <div class="wid23AlignC content-text12Lh20">:</div>
                <div class="floatLeft">
                    <div class="clearBoth content-text12Lh20">Type the characters you see in the picture below.</div>
                    <div class="lh5">&nbsp;</div>
                    <div class="clearBoth">
                        <div class="floatLeft">
                                <div class="floatLeft jCaptcha"><?php  echo recaptcha_get_html($this->publickey, $errorRecaptcha); ?></div>
                        </div>
                    </div>
                    <div class="lh20">&nbsp;</div>
                    <div class="clearBoth">
                      <!--  <form action="forgot_your_password_instruction.php" method="post">
                            <input type="image" src="images/send_instructions_btn.gif" class="cursor" title="Send Instructions" />
                         </form>-->
                      <input type="submit" class="forgetpasswordBtn" title="Send Instructions"  id="submit"  value="" name="submit" />
                    </div>
                </div>
            </div>
            <div class="lh35">&nbsp;</div>
        </div>
        <div class="forgot_seperator">&nbsp;</div>
        <div class="wid252">
        	<div class="clearBoth grey-text12Lh20"> We will send password reset instruction to the email address associated with your account.</div>
            <div class="lh20">&nbsp;</div>
            <div class="clearBoth"><a href="javascript:history.go(-1)" title="Back" class="hyperLinkBlue14">Back</a></div>
       	</div>
    </div>
              <input type="hidden" name="forgetpasspage" value="forgetpasswordvalue">
              <input type="hidden" name="newvcode" value="<?php echo $this->vcodes; ?>">
              <input type="hidden" name="forgetpasscodes" value="<?php echo $this->forgetpass; ?>">
              <input type="hidden" name="user_full_name" value="<?php echo $this->userfullname; ?>">
     </form>
</div>
