<table cellpadding="0" cellspacing="0" align="center" width="1000">
	<tr>
    	<!--Right panel starts from here-->
    	<td width="260" valign="top">
        	<div class="bank_accountLeftPanel">
            	<div class="lh25">&nbsp;</div>
            	<div class="businessDetialsLeftPanel">
					
               <?php
			 		$request = Zend_Controller_Front::getInstance()->getRequest();
					$controllerName = $request->getControllerName();
					$actionName = $request->getActionName();
					$genObj = new General();
					//$controllerName = "Store";
					$abc = $genObj->displaySettingMenuNew($controllerName,$actionName);
					echo $abc;
				?>
                
            	</div>
            </div>
        </td>
        <!--Right panel ends from here-->
        <!--Left panel starts from here-->
        <td width="740" valign="top">
        	<div class="bank_accountRightPanel">
                <div class="lh25">&nbsp;</div>
                
                <div class="clearBoth">
                	<div class="floatLeft">
                        <div class="floatLeft blueMainHeading">My payment</div>
                        <div class="navArrow">&nbsp;</div>
                        <div class="floatLeft content_text15Lh25"><b>Bank account confirmed</b></div>
                    </div>
                    <div class="floatRight">
                    	<div class="backArrow"></div>
                        <div class="floatLeft"><a href="/mypayment/bankaccountlisting" class="hyperLinkBlue13" title="Back to my payment">Back to my payment</a></div>
                    </div>
                </div>
                <div class="lh25">&nbsp;</div>
                <div class="congratulationsContainer">Congratulations!! You have successfully confirmed your bank account <?php echo $this->bankaccountDetails[0]['bankname']; ?>, XX-<?php echo substr($this->bankaccountDetails[0]['account_number'],-4,4);?></div>
                <div class="lh25">&nbsp;</div>
                <div class="floatLeft greyText12Lh20">You have successfully confirmed your bank details with the amount deposited by Goo2o Now you are eligible to receive payments   and withdraw amounts for all your transactions made on any of the goo2o stores.</div>
                <div class="lh40">&nbsp;</div>
              	<div class="floatLeft"><a href="/mypayment/bankaccountlisting"><img  src="/images/secure/continue_button.png" title="Continue" /></a></div> 
               <div class="lh40">&nbsp;</div>
                
           </div>
        
        </td>
        <!--Left panel ends from here-->
    </tr>
</table>