<table cellpadding="0" cellspacing="0" align="center" width="1000">
	<tr>
    	<!--LEFT PANEL starts from here-->
    	<td width="260" valign="top">
        	<div class="bank_account_listingLeftPanel">
            	<div class="lh25">&nbsp;</div>
            	<div class="businessDetialsLeftPanel">

                <?php  
					$request = Zend_Controller_Front::getInstance()->getRequest();
					$controllerName = $request->getControllerName();
					$actionName = $request->getActionName();
					$genObj = new General();
					//$controllerName = "Store";
					$abc = $genObj->displaySettingMenuNew($controllerName,$actionName);
					echo $abc;
				?>
                </div>
            </div>
        </td>
        <!--LEFT PANELends from here-->
        <!--RIGHT PANEL starts from here-->
        <td width="740" valign="top">
        	<div class="bank_account_listingRightPanel">
                <div class="lh25">&nbsp;</div>
                
                <div class="clearBoth">
                	<div class="floatLeft">
                        <div class="floatLeft blueMainHeading">My payment</div>
                        
                    </div>
                    <div class="floatRight"></div>
                </div>
                <div class="lh25">&nbsp;</div>
                <div class="clearBoth">
                	<div class="clearBoth content_text12">Add your bank account to receive your payments and withdrawals resulted from the transactions made on goo2o stores like;</div>
                    <div class="lh10">&nbsp;</div>
                    <div class="clearBoth">
                    	<div class="squareBullet">&nbsp;</div>
                        <div class="floatLeft content_text12">Receive payments for the products sold from your store.</div>
                    </div>
                    <div class="lh10">&nbsp;</div>
                    <div class="clearBoth">
                    	<div class="squareBullet">&nbsp;</div>
                        <div class="floatLeft content_text12">Withdraw amount during a refund for the products purchased from any of the goo2o stores.</div>
                    </div>
                </div>
                <div class="lh35">&nbsp;</div>
                <div class="clearBoth greyText12Lh20">Your account information details will be kept confidential by storing it in our secure servers.</div>
               	<div class="lh20">&nbsp;</div>
                <div class="clearBoth content_text12Lh25"><span class="floatLeft">To add a new bank account, click on &nbsp;&nbsp;</span><span class="floatLeft"><a href="/mypayment/addabankaccount"><img src="/images/secure/add_a_bank_account_btn.png" title="Add a bank account" /></a></span></div>
               <div class="lh40">&nbsp;</div>
                
           </div>
        
        </td>
        <!--RIGHT PANEL ends from here-->
    </tr>
</table>