<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Mail Format</title>
<style type="text/css">
body{margin:0px; padding:0px;}
.fs0{font-size:0px;}
img{border:0px none;}
.table_border{border:5px solid #C0DEED;}
.height80{height:80px;}
.header_bgcolor{background-color:#C0DEED; }
.name_heading{font-family:"Trebuchet MS", Arial, helvetica; font-size:16px; color:#393939; font-weight:bold;}
.normal_text{font-family:"Trebuchet MS", Arial, helvetica; font-size:12px; color:#393939;}
a.activate_link{font-family:"Trebuchet MS", Arial, helvetica; font-size:13px; color:#196B7B; text-decoration:underline;}
a:hover.activate_link{font-family:"Trebuchet MS", Arial, helvetica; font-size:13px; color:#196B7B; text-decoration:none;}
.iglobul_team{font-family:Georgia, "Times New Roman", Times, serif; font-size:13px; color:#666666; font-style:italic;}
.underline{height:1px; line-height:1px; background-color:#EEEEEE; font-size:0px;}
.notification_text{color:#888888; font-family:"Trebuchet MS", Arial, helvetica; font-size:11px;}
a.iglobul_support{color:#196B7B; font-family:"Trebuchet MS", Arial, helvetica; font-size:11px; text-decoration:underline;}
a:hover.iglobul_support{color:#196B7B; font-family:"Trebuchet MS", Arial, helvetica; font-size:11px; text-decoration:none;}
.igb_name{font-family:"Trebuchet MS", Arial, helvetica; font-size:20px; color:#000000; text-align:right; font-weight:bold;}
.paddleft40{padding-left:40px;}
.fs11{font-size:11px;}
.fwb{font-weight:bold;}
</style>
</head>

<body>
<table cellpadding="0" cellspacing="0" border="0" width="805" align="center" class="table_border">
		<tr>
		<td valign="top">
			<table cellpadding="0" cellspacing="0" border="0" width="770" align="center">
                                <tr>
                                    <td valign="top" class="name_heading fs12"><b>Forget Password</b></td>
				</tr>
				<tr>
					<td valign="top" class="name_heading fs12">Dear&nbsp;<span><b><?php echo $this->name; ?>
,</b></span></td>
				</tr>

				<tr>
					<td height="10" class="fs0">&nbsp;</td>
				</tr>
				<tr>
					<td class="normal_text">We received a request to reset the password for your Goo2o account.</td>
				</tr>
                            <tr>
					<td class="normal_text">If you want to reset your password, click on the link below (or copy and paste the URL into your browser):</td>
				</tr>
                             
                                <tr>
					<td class="normal_text"><span style="color:#FF0000"><a href="<?php echo $this->link; ?>">Change Password</a></span></td>
				</tr>
				<tr>
					<td class="normal_text">This link takes you to a secure page where you can change your password. If you don't want to reset your password, please ignore this message. Your password will not be reset.</td>
				</tr>
                                <tr>
					<td class="normal_text">Regards,</td>
				</tr>
                   <tr>
					<td class="iglobul_team">The Goo2o Team</td>
				</tr>
                
			</table>
		</td>
	</tr>

</table>
</body>
</html>

