<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Mail Format</title>
<style type="text/css">
body{margin:0px; padding:0px;}
.fs0{font-size:0px;}
img{border:0px none;}
.table_border{border:5px solid #C0DEED;}
.height80{height:80px;}
.header_bgcolor{background-color:#C0DEED; }
.name_heading{font-family:"Trebuchet MS", Arial, helvetica; font-size:16px; color:#393939; font-weight:bold;}
.normal_text{font-family:"Trebuchet MS", Arial, helvetica; font-size:12px; color:#393939;}
a.activate_link{font-family:"Trebuchet MS", Arial, helvetica; font-size:13px; color:#196B7B; text-decoration:underline;}
a:hover.activate_link{font-family:"Trebuchet MS", Arial, helvetica; font-size:13px; color:#196B7B; text-decoration:none;}
.iglobul_team{font-family:Georgia, "Times New Roman", Times, serif; font-size:13px; color:#666666; font-style:italic;}
.underline{height:1px; line-height:1px; background-color:#EEEEEE; font-size:0px;}
.notification_text{color:#888888; font-family:"Trebuchet MS", Arial, helvetica; font-size:11px;}
a.iglobul_support{color:#196B7B; font-family:"Trebuchet MS", Arial, helvetica; font-size:11px; text-decoration:underline;}
a:hover.iglobul_support{color:#196B7B; font-family:"Trebuchet MS", Arial, helvetica; font-size:11px; text-decoration:none;}
.igb_name{font-family:"Trebuchet MS", Arial, helvetica; font-size:20px; color:#000000; text-align:right; font-weight:bold;}
.paddleft40{padding-left:40px;}
.fs11{font-size:11px;}
.fwb{font-weight:bold;}
</style>
</head>

<body>
<table cellpadding="0" cellspacing="0" border="0" width="805" align="center" class="table_border">
	<tr>
		<td valign="top">
		</td>
	</tr>
	<tr>
		<td valign="top">
			<table cellpadding="0" cellspacing="0" border="0" width="770" align="center">
				<tr>
					<td valign="top" class="name_heading fs12">Dear&nbsp;<span><b><?php echo $this->name; ?>
,</b></span></td>
				</tr>
				
				<tr>
					<td height="10" class="fs0">&nbsp;</td>
				</tr>
				<tr>
					<td class="normal_text">To complete your signup process on Goo2o,you must veryfy your email address.</td>
				</tr>
                <tr>
					<td height="10" class="fs0">&nbsp;</td>
				</tr>
                <tr>
					<td class="normal_text"><span style="color:#FF0000"><a href="<?php echo $this->link; ?>">Click here to veryfy your account</a></span></td>
				</tr>
				<tr>
					<td class="normal_text">Once you confirm , you will have full accesss to to Goo2o and all future notifications will be sent to this email address.Be sure to add do-not-reply@gogo2o.com to your address book or safe sender list so our emails get to your inbox.</td>
				</tr>
                <tr>
					<td class="normal_text">In case of any suggestions or queries,please feel free to contact at anytime</td>
				</tr>
                 <tr>
					<td class="normal_text">Our Helpline numbers:</td>
				</tr>
                   <tr>
					<td class="normal_text"><a href="mailto:support@goo2o.com">Email:support@goo2o.com</a></td>
				</tr>
                <tr>
					<td class="normal_text">For help,guidelines or rules,visit Goo2o Support Desk</td>
				</tr>
                  <tr>
					<td class="normal_text">Submit a support request if you have any problem with your Goo2o account.You can check your request status anytime by logging in to our support desk.</td>
				</tr>
                <tr>
					<td class="normal_text">Regards,</td>
				</tr>
                   <tr>
					<td class="iglobul_team">The Goo2o Team</td>
				</tr>
                <tr>
					<td class="normal_text">Please do not reply to this message; it was sent from an unmonitored email address.This message is service email related to your use of Goo2o.For general inquiries or to request support with your Goo2o account,please visit us at <a href="http://goo2o.com/">Goo2o Support</a>.In case you did not sign up with us & still received thi mail,click <a href="<?php echo $this->notmyaccountlinks; ?>">not my account</a> and stop recieving future mails.</td>
				</tr>

			</table>
		</td>
	</tr>
	
</table>
</body>
</html>

