<table cellpadding="0" cellspacing="0" border="0" width="805">
  <tr>
    <td valign="top"><table cellpadding="0" cellspacing="0" border="0" width="770">
		<tr>
          <td height="10" style="font-size:0px;">&nbsp;</td>
        </tr>
        <tr>
          <td valign="top" style="font-family:Trebuchet MS, Arial, helvetica; font-size:13px; color:#393939; font-weight:bold; ">IGB Reference</td>
        </tr>
        <tr>
          <td height="10" style="font-size:0px;">&nbsp;</td>
        </tr>
        <tr>
          <td valign="top" style="font-family:Trebuchet MS, Arial, helvetica; font-size:13px; color:#393939; font-weight:bold; ">Dear $USERNAME,</td>
        </tr>
        <tr>
          <td height="15" style="font-size:0px;">&nbsp;</td>
        </tr>
        <tr>
          <td valign="top" style="font-family:Trebuchet MS, Arial, helvetica; font-size:13px; color:#393939;">Thanks for joining iglobul...! We have verified and created your account successfully. Now you can buy & sell live deals with real-time conversation.</td>
        </tr>
        <tr>
          <td height="15" style="font-size:0px;">&nbsp;</td>
        </tr>
        <tr>
          <td valign="top" style="font-size:0px;font-family:Trebuchet MS, Arial, helvetica; font-size:13px; color:#393939; font-weight:bold">Top 5 things that will get you the most of it:</td>
        </tr>
        <tr>
          <td height="15" style="font-size:0px;">&nbsp;</td>
        </tr>
        <tr>
          <td style="font-family:Trebuchet MS, Arial, helvetica; font-size:13px; color:#393939;">
		  <ol>
              <li>Edit your profile to help others identify you.</li>
              <li>Start participating by posting your need to get instant reverts.</li>
              <li>Browse hot deals in your location and publish a deal, if you have one.</li>
              <li>Share tips, recommendations, campaigns with the community.</li>
              <li>Alternatively, activate iglobul mobile to get updates by SMS.</li>
            </ol></td>
        </tr>
        <tr>
          <td height="15" style="font-size:0px;">&nbsp;</td>
        </tr>
        <tr>
          <td style="font-family:Trebuchet MS, Arial, helvetica; font-size:13px; color:#393939;">Regards,</td>
        </tr>
        <tr>
          <td style="font-family:Trebuchet MS, Arial, helvetica; font-size:13px; color:#393939;"> The iGlobul Team</td>
        </tr>
        <tr>
          <td height="15" style="font-size:0px;">&nbsp;</td>
        </tr>
      </table></td>
  </tr>
  <tr>
    <td><table cellpadding="0" cellspacing="0" border="0" width="770">
        <tr>
          <td style="height:1px; line-height:1px; background-color:#EEEEEE; font-size:0px;"></td>
        </tr>
       $FOOTER_OPTIONAL
        <tr>
          <td height="5" style="font-size:0px;">&nbsp;</td>
        </tr>
      </table></td>
  </tr>
</table>


