<table cellpadding="0" cellspacing="0" border="0" width="760" align="center">
	<tr>
		<td height="27">&nbsp;</td>
	</tr>
	<tr>
    	<td valign="bottom">
            <div class="wid92"><a href="<?=HTTP_SERVER_ROOTS?>"><img src="/images/secure/logo.gif" /></a></div>
            <div class="floatLeft header_txt" style="padding-top:30px;">iglobul helps you buy & sell live deals with real-time conversation. </div>
    	</td>
    </tr>
    <tr>
    	<td height="10" class="fs0">&nbsp;</td>
    </tr>
    <tr>
    	<td class="step_bg">&nbsp;</td>
    </tr>
    <tr>
    	<td height="40" class="fs0">&nbsp;</td>
    </tr>
    <tr>
        <td valign="top">
			<div class="clearBoth subscribe_heading">Get updates on your phone.</div>
		</td>
    </tr>

    <tr>
    	<td height="23" class="fs0">&nbsp;</td>
    </tr>
    <tr>
    	<td valign="top" class="register">
        	Register for iGlobul Text Messages
        </td>
    </tr>
    <tr>
    	<td height="2">
        	<div class="clearBoth dashed fs0">&nbsp;</div>
        </td>
    </tr>
    <tr>
    	<td height="25">&nbsp;</td>
    </tr>
    <tr>
    	<td>
        	<div class="clearBoth">
            	<div class="wid50">&nbsp;</div>
                <div class="wid132 mobile_no">Mobile No.</div>
                <div class="wid16 mobile_no">:</div>
                <div class="floatLeft">+91 <input type="text" class="input_in" name="mobileno" id="mobileno"/></div>
				<div class="floatLeft padLeft7 alert"></div>
            </div>
			<div id="inputMsgmobileno" class="alert"></div>
            <div class="lh8">&nbsp;</div>
            <div class="clearBoth">
            	<div class="wid50">&nbsp;</div>
                <div class="wid132 mobile_no">Re-enter Mobile No.</div>
                <div class="wid16 mobile_no">:</div>
                <div class="floatLeft">+91 <input type="text" class="input_in" name="remobileno" id="remobileno"/></div>
			</div>
			<div id="inputMsgremobile" class="alert"></div>
			<!--<div class="clearBoth" id="mainerror" style="display:none;" >
				<div class="floatLeft" style="width:220px;">&nbsp;</div>
				<div class="floatLeft alert" id="validation" style="width:440px;" >&nbsp;</div>
			</div>-->
			 <div class="lh14">&nbsp;</div>
            <div class="clearBoth">
            	<div class="wid220">&nbsp;</div>
                <div class="floatLeft"><input type="image" src="/images/secure/confirmation_code_btn.gif" title="Get Activation Code" alt="Get Activation Code" class="confirmmobile" /></div>
				<div class="floatLeft" id="showMeassage"></div>
            </div>
        </td>
    </tr>
    <tr>
    	<td height="50">&nbsp;</td>
    </tr>
    <tr>
    	<td valign="top" class="register">
        	Received an activation code?
        </td>
    </tr>
    <tr>
    	<td height="2">
        	<div class="clearBoth dashed fs0">&nbsp;</div>
        </td>
    </tr>
    <tr>
    	<td height="25">&nbsp;</td>
    </tr>
   <tr>
    	<td>
        	<div class="clearBoth">
            	<div class="wid50">&nbsp;</div>
                <div class="wid132 mobile_no">Activation Code</div>
                <div class="wid16 mobile_no">:</div>
                <div class="floatLeft"><input type="text" class="input_in_111" name="confirmcode" id="confirmcode"/></div>
                <div class="wid30">&nbsp;</div>
                <div class="floatLeft"><input type="image" name="active" src="/images/secure/confirm_btn_mobile.gif" title="Confirm" alt="Confirm" class="confirm" /></div>
            </div>
			<div id="inputMsgsubmitCode" class="alert" style="color:#FF0000" ></div>
			<div class="clearBoth" id="confirmerror" style="display:none;" >
				<div class="floatLeft" style="width:190px;">&nbsp;</div>
				<div class="floatLeft padLeft7 alert" id="valconfirm">&nbsp;</div>
			</div>
        </td>
    </tr>
    <tr>
    	<td height="95">&nbsp;</td>
    </tr>
    <tr>
    	<td class="note"><strong>Note:</strong> If you have not received the activation code, skip this step .You can register your mobile number later from your settings.</td>
    </tr>
    <tr>
    	<td height="35" class="fs0">&nbsp;</td>
    </tr>
    <tr>
    	<td valign="top">
        	<div class="clearBoth">
            	<div class="wid446">
                	<a href="verifyyourself">
						<div class="next_step"></div></a>
						<div class="wid9">&nbsp;</div>
						<a href="verifyyourself" class="skip_link"><div class="skip_step">&nbsp;</div></a>
                </div>
                <div class="floatRight">&nbsp;</div>
            </div>
        </td>
    </tr>
	<tr>
    	<td height="30" class="fs0">&nbsp;</td>
    </tr>
</table>
