<table cellpadding="0" cellspacing="0" border="0" width="760" align="center">
	<tr>
		<td height="27">&nbsp;</td>
	</tr>
	<tr>
    	<td valign="bottom">
            <div class="wid92"><a href="<?=HTTP_SERVER_ROOTS?>"><img src="/images/secure/logo.gif" /></a></div>
            <div class="floatLeft header_txt" style="padding-top:30px;">iglobul helps you buy & sell live deals with real-time conversation. </div>
    	</td>
    </tr>
    <tr>
    	<td height="10" class="fs0">&nbsp;</td>
    </tr>
    <tr>
    	<td class="add_profile_info">&nbsp;</td>
    </tr>
    <tr>
    	<td height="40" class="fs0">&nbsp;</td>
    </tr>
    <tr>
        <td valign="top">
			<div class="clearBoth subscribe_heading">Setup your profile.</div>
		</td>
    </tr>

    <tr>
    	<td height="23" class="fs0">&nbsp;</td>
    </tr>
    <tr>
    	<td valign="top" class="register">
        	Upload a profile picture:
        </td>
    </tr>
    <tr>
    	<td height="2">
        	<div class="clearBoth dashed fs0">&nbsp;</div>
        </td>
    </tr>
    <tr>
    	<td height="10">&nbsp;</td>
    </tr>
    <tr>
    	<td>
	<!--	<div id="showImgInfo" class="floatLeft imgText" style="border:1px solid; width:150px; height:16px;">&nbsp;</div>-->
		<input type="hidden" name="returnImg" id="returnImg">
		<input type="hidden" name="returnDefImg" id="returnDefImg">
		<input type="hidden" name="returnwidth" id="returnwidth">
		<input type="hidden" name="returnheight" id="returnheight">
		<input type="hidden" name="returnwidthedit" id="returnwidthedit">
		<input type="hidden" name="returnheightedit" id="returnheightedit">

        	<div class="clearBoth">
            	<div class="wid25">&nbsp;</div>
                <div class="wid129">
                	<div class="floatLeft" id="showImgInfo"><img src="/images/secure/default_image.gif" border="0" /></div>
                </div>
                <div class="floatLeft">
                	<div class="clearBoth">
                		<div class="clearBoth" align="center" title="Upload a photo"><a class="upload" id="uploadaphoto">Upload a photo</a></div>
                    	<div class="clearBoth upload_under_txt" align="center">from your computer</div>
                    </div>
                    <div class="lh15">&nbsp;</div>
                    <div class="clearBoth" align="center">
                    	<div class="floatLeft bg_lin">&nbsp;</div>
                        <div class="floatLeft or marTop10" align="center">or</div>
                        <div class="floatLeft bg_lin">&nbsp;</div>
                    </div>
                    <div class="lh6">&nbsp;</div>
                    <div class="clearBoth">
                		<div class="clearBoth" align="center" title="Select an avatar"><a  class="upload">Select an avatar</a></div>
                    	<div class="clearBoth upload_under_txt" align="center">from our design stock</div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
    <tr>
    	<td height="50" class="fs0">&nbsp;</td>
    </tr>
    <tr>
    	<td valign="top" class="register">
        	Write a short bio:
        </td>
    </tr>
    <tr>
    	<td height="2">
        	<div class="clearBoth dashed fs0">&nbsp;</div>
        </td>
    </tr>
    <tr>
    	<td height="25">&nbsp;</td>
    </tr>
   <tr>
    	<td>
        	<div class="clearBoth">
            	<div class="wid25">&nbsp;</div>
                <div class="floatLeft">
                	<div class="clearBoth">
                		<textarea name="shortnote" id="shortnote" data-maxsize="10"></textarea>
                    </div>
                    <div class="clearBoth upload_under_txt">About you in less than 160 characters.</div>
                </div><span class="charcounter">160</span>
            </div>
        </td>
    </tr>
    <tr>
    	<td height="50">&nbsp;</td>
    </tr>
    <tr>
    	<td valign="top">
        		<div class="wid450">
                	<!--<a href="index.php?main_page=set_your_preference"><div class="next_step"></div></a>-->
					<div class="next_step redirect">&nbsp;</div>
					<div class="wid9">&nbsp;</div>
					<div class="skip_step redirect">&nbsp;</div>
            	</div>
        </td>
    </tr>
	<tr>
    	<td colspan="3" height="30" class="fs0">&nbsp;</td>
    </tr>
</table>